package com.luoboduner.moo.tool.ui.form.func;

import cn.hutool.core.util.ObjectUtil;
import cn.hutool.log.Log;
import cn.hutool.log.LogFactory;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.luoboduner.moo.tool.util.UndoUtil;
import lombok.Getter;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

/**
 * <pre>
 * ColorBoardForm
 * </pre>
 *
 * @author <a href="https://github.com/rememberber">RememBerBer</a>
 * @since 2019/11/13.
 */
@Getter
public class ColorBoardForm {
    private JPanel colorBoardPanel;
    private JButton 取色器Button;
    private JComboBox comboBox1;
    private JTextField textField1;
    private JButton 复制Button;
    private JPanel showColorPanel;
    private JButton 收藏Button;
    private JButton 收藏夹Button;
    private JPanel standardColorPanel;
    private JPanel themeColorPanel;
    private JComboBox comboBox2;
    private JPanel themeColorMainPanel;
    private JPanel themColorSubPanel0;
    private JPanel themColorSubPanel1;
    private JPanel themColorSubPanel2;
    private JPanel themColorSubPanel3;
    private JPanel themColorSubPanel4;
    private JPanel themColorSubPanel5;
    private JPanel themColorSubPanel6;
    private JPanel themColorSubPanel7;
    private JPanel themColorSubPanel8;
    private JPanel themColorSubPanel9;

    private static ColorBoardForm colorBoardForm;

    private static final Log logger = LogFactory.get();

    private ColorBoardForm() {
        UndoUtil.register(this);
    }

    public static ColorBoardForm getInstance() {
        if (colorBoardForm == null) {
            colorBoardForm = new ColorBoardForm();
        }
        return colorBoardForm;
    }

    public static void init() {
        colorBoardForm = getInstance();
        colorBoardForm.getShowColorPanel().setBackground(new Color(163, 73, 164));

        Dimension dimension = new Dimension(50, 50);
        for (int i = 0; i < 10; i++) {
            JPanel panel = new JPanel();
            switch (i) {
                case 0:
                    panel.setBackground(new Color(192, 0, 0));
                    break;
                case 1:
                    panel.setBackground(new Color(255, 0, 0));
                    break;
                case 2:
                    panel.setBackground(new Color(255, 192, 0));
                    break;
                case 3:
                    panel.setBackground(new Color(255, 255, 0));
                    break;
                case 4:
                    panel.setBackground(new Color(146, 208, 80));
                    break;
                case 5:
                    panel.setBackground(new Color(0, 176, 80));
                    break;
                case 6:
                    panel.setBackground(new Color(0, 176, 240));
                    break;
                case 7:
                    panel.setBackground(new Color(0, 112, 192));
                    break;
                case 8:
                    panel.setBackground(new Color(0, 32, 96));
                    break;
                case 9:
                    panel.setBackground(new Color(112, 48, 160));
                    break;
                default:
                    break;

            }
            panel.setSize(dimension);
            panel.setPreferredSize(dimension);
            colorBoardForm.getStandardColorPanel().add(panel);
            colorBoardForm.getThemeColorMainPanel().add(ObjectUtil.cloneByStream(panel));
            colorBoardForm.getThemColorSubPanel0().add(ObjectUtil.cloneByStream(panel));
            colorBoardForm.getThemColorSubPanel1().add(ObjectUtil.cloneByStream(panel));
            colorBoardForm.getThemColorSubPanel2().add(ObjectUtil.cloneByStream(panel));
            colorBoardForm.getThemColorSubPanel3().add(ObjectUtil.cloneByStream(panel));
            colorBoardForm.getThemColorSubPanel4().add(ObjectUtil.cloneByStream(panel));
            colorBoardForm.getThemColorSubPanel5().add(ObjectUtil.cloneByStream(panel));
            colorBoardForm.getThemColorSubPanel6().add(ObjectUtil.cloneByStream(panel));
            colorBoardForm.getThemColorSubPanel7().add(ObjectUtil.cloneByStream(panel));
            colorBoardForm.getThemColorSubPanel8().add(ObjectUtil.cloneByStream(panel));
            colorBoardForm.getThemColorSubPanel9().add(ObjectUtil.cloneByStream(panel));
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        colorBoardPanel = new JPanel();
        colorBoardPanel.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 10, 10, 10), -1, -1));
        colorBoardPanel.add(panel1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        themeColorPanel = new JPanel();
        themeColorPanel.setLayout(new GridLayoutManager(3, 1, new Insets(5, 5, 5, 5), -1, -1));
        panel2.add(themeColorPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        themeColorPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), "主题颜色", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, this.$$$getFont$$$(null, Font.BOLD, -1, themeColorPanel.getFont())));
        comboBox2 = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("默认");
        defaultComboBoxModel1.addElement("主题1");
        defaultComboBoxModel1.addElement("主题2");
        comboBox2.setModel(defaultComboBoxModel1);
        themeColorPanel.add(comboBox2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        themeColorMainPanel = new JPanel();
        themeColorMainPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        themeColorPanel.add(themeColorMainPanel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        themeColorPanel.add(panel3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        themColorSubPanel0 = new JPanel();
        themColorSubPanel0.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 0));
        themColorSubPanel0.setMaximumSize(new Dimension(50, 500));
        themColorSubPanel0.setMinimumSize(new Dimension(50, 500));
        themColorSubPanel0.setPreferredSize(new Dimension(50, 500));
        panel3.add(themColorSubPanel0);
        themColorSubPanel1 = new JPanel();
        themColorSubPanel1.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 0));
        themColorSubPanel1.setMaximumSize(new Dimension(50, 500));
        themColorSubPanel1.setMinimumSize(new Dimension(50, 500));
        themColorSubPanel1.setPreferredSize(new Dimension(50, 500));
        panel3.add(themColorSubPanel1);
        themColorSubPanel2 = new JPanel();
        themColorSubPanel2.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 0));
        themColorSubPanel2.setMaximumSize(new Dimension(50, 500));
        themColorSubPanel2.setMinimumSize(new Dimension(50, 500));
        themColorSubPanel2.setPreferredSize(new Dimension(50, 500));
        panel3.add(themColorSubPanel2);
        themColorSubPanel3 = new JPanel();
        themColorSubPanel3.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 0));
        themColorSubPanel3.setMaximumSize(new Dimension(50, 500));
        themColorSubPanel3.setMinimumSize(new Dimension(50, 500));
        themColorSubPanel3.setPreferredSize(new Dimension(50, 500));
        panel3.add(themColorSubPanel3);
        themColorSubPanel4 = new JPanel();
        themColorSubPanel4.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 0));
        themColorSubPanel4.setMaximumSize(new Dimension(50, 500));
        themColorSubPanel4.setMinimumSize(new Dimension(50, 500));
        themColorSubPanel4.setPreferredSize(new Dimension(50, 500));
        themColorSubPanel4.setRequestFocusEnabled(false);
        panel3.add(themColorSubPanel4);
        themColorSubPanel5 = new JPanel();
        themColorSubPanel5.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 0));
        themColorSubPanel5.setMaximumSize(new Dimension(50, 500));
        themColorSubPanel5.setMinimumSize(new Dimension(50, 500));
        themColorSubPanel5.setPreferredSize(new Dimension(50, 500));
        panel3.add(themColorSubPanel5);
        themColorSubPanel6 = new JPanel();
        themColorSubPanel6.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 0));
        themColorSubPanel6.setMaximumSize(new Dimension(50, 500));
        themColorSubPanel6.setMinimumSize(new Dimension(50, 500));
        themColorSubPanel6.setPreferredSize(new Dimension(50, 500));
        panel3.add(themColorSubPanel6);
        themColorSubPanel7 = new JPanel();
        themColorSubPanel7.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 0));
        themColorSubPanel7.setMaximumSize(new Dimension(50, 500));
        themColorSubPanel7.setMinimumSize(new Dimension(50, 500));
        themColorSubPanel7.setPreferredSize(new Dimension(50, 500));
        panel3.add(themColorSubPanel7);
        themColorSubPanel8 = new JPanel();
        themColorSubPanel8.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 0));
        themColorSubPanel8.setMaximumSize(new Dimension(50, 500));
        themColorSubPanel8.setMinimumSize(new Dimension(50, 500));
        themColorSubPanel8.setPreferredSize(new Dimension(50, 500));
        panel3.add(themColorSubPanel8);
        themColorSubPanel9 = new JPanel();
        themColorSubPanel9.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 0));
        themColorSubPanel9.setMaximumSize(new Dimension(50, 500));
        themColorSubPanel9.setMinimumSize(new Dimension(50, 500));
        themColorSubPanel9.setPreferredSize(new Dimension(50, 500));
        panel3.add(themColorSubPanel9);
        final Spacer spacer1 = new Spacer();
        panel3.add(spacer1);
        standardColorPanel = new JPanel();
        standardColorPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        panel2.add(standardColorPanel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        standardColorPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), "标准颜色", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, this.$$$getFont$$$(null, Font.BOLD, -1, standardColorPanel.getFont())));
        showColorPanel = new JPanel();
        showColorPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 10, 0, 0), -1, -1));
        panel1.add(showColorPanel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        showColorPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(1, 7, new Insets(10, 10, 10, 10), -1, -1));
        colorBoardPanel.add(panel4, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        取色器Button = new JButton();
        取色器Button.setIcon(new ImageIcon(getClass().getResource("/icon/color_picker.png")));
        取色器Button.setText("取色器");
        panel4.add(取色器Button, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel4.add(spacer2, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        comboBox1 = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        defaultComboBoxModel2.addElement("HTML");
        defaultComboBoxModel2.addElement("html");
        defaultComboBoxModel2.addElement("RGB");
        comboBox1.setModel(defaultComboBoxModel2);
        panel4.add(comboBox1, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textField1 = new JTextField();
        panel4.add(textField1, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(100, -1), null, 0, false));
        复制Button = new JButton();
        复制Button.setIcon(new ImageIcon(getClass().getResource("/icon/copy.png")));
        复制Button.setText("复制");
        panel4.add(复制Button, new GridConstraints(0, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        收藏Button = new JButton();
        收藏Button.setIcon(new ImageIcon(getClass().getResource("/icon/star-empty.png")));
        收藏Button.setText("收藏");
        panel4.add(收藏Button, new GridConstraints(0, 6, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        收藏夹Button = new JButton();
        收藏夹Button.setIcon(new ImageIcon(getClass().getResource("/icon/favorite.png")));
        收藏夹Button.setText("收藏夹");
        panel4.add(收藏夹Button, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JSeparator separator1 = new JSeparator();
        colorBoardPanel.add(separator1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, 1, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return colorBoardPanel;
    }

}
