package com.luoboduner.moo.tool.ui.form.func;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.luoboduner.moo.tool.domain.TFuncHistory;
import com.luoboduner.moo.tool.ui.FuncConsts;
import com.luoboduner.moo.tool.ui.Style;
import com.luoboduner.moo.tool.ui.component.FuncHistoryPanel;
import com.luoboduner.moo.tool.ui.listener.func.YmlPropertiesListener;
import com.luoboduner.moo.tool.util.FuncHistorySupport;
import com.luoboduner.moo.tool.util.UndoUtil;
import org.apache.commons.lang3.StringUtils;
import lombok.Getter;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ComponentAdapter;

/**
 * <pre>
 * yml配置文件和properties文件转换
 * </pre>
 *
 * @author <a href="https://github.com/rememberber">RememBerBer</a>
 * @since 2019/9/9.
 */
@Getter
public class YmlPropertiesForm {
    private JTabbedPane tabbedPane1;
    private JPanel ymlPropertiesPanel;
    private JTextArea propertiesTextArea;
    private JTextArea ymlTextArea;
    private JButton properties2ymlButton;
    private JButton yml2propertiesButton;
    private JTextArea yamlValidateInputTextArea;
    private JTextArea yamlValidateResultTextArea;
    private JButton yamlValidateButton;
    private JButton yamlFormatButton;

    private static YmlPropertiesForm ymlPropertiesForm;

    private static FuncHistoryPanel historyPanel;

    public static YmlPropertiesForm getInstance() {
        if (ymlPropertiesForm == null) {
            ymlPropertiesForm = new YmlPropertiesForm();
        }
        return ymlPropertiesForm;
    }

    private YmlPropertiesForm() {
        UndoUtil.register(this);
        propertiesTextArea.addComponentListener(new ComponentAdapter() {
        });
    }

    public static void init() {
        ymlPropertiesForm = getInstance();
        initUi();
        historyPanel = FuncHistorySupport.attachTab(
                ymlPropertiesForm.getTabbedPane1(), FuncConsts.YML_PROPERTIES, YmlPropertiesForm::applyHistory);

        YmlPropertiesListener.addListeners();
    }

    public static FuncHistoryPanel getHistoryPanel() {
        return historyPanel;
    }

    public static void applyHistory(TFuncHistory history) {
        if (history == null || StringUtils.isBlank(history.getExtraData())) {
            return;
        }
        switch (history.getExtraData()) {
            case "Prop2Yml" -> {
                ymlPropertiesForm.getPropertiesTextArea().setText(history.getInputText());
                ymlPropertiesForm.getYmlTextArea().setText(history.getOutputText());
                ymlPropertiesForm.getTabbedPane1().setSelectedIndex(0);
            }
            case "Yml2Prop" -> {
                ymlPropertiesForm.getYmlTextArea().setText(history.getInputText());
                ymlPropertiesForm.getPropertiesTextArea().setText(history.getOutputText());
                ymlPropertiesForm.getTabbedPane1().setSelectedIndex(0);
            }
            case "YamlValidate" -> {
                ymlPropertiesForm.getYamlValidateInputTextArea().setText(history.getInputText());
                ymlPropertiesForm.getYamlValidateResultTextArea().setText(history.getOutputText());
                ymlPropertiesForm.getTabbedPane1().setSelectedIndex(1);
            }
            case "YamlFormat" -> {
                ymlPropertiesForm.getYamlValidateInputTextArea().setText(history.getOutputText());
                ymlPropertiesForm.getYamlValidateResultTextArea().setText(history.getInputText());
                ymlPropertiesForm.getTabbedPane1().setSelectedIndex(1);
            }
            default -> {
            }
        }
    }

    private static void initUi() {
        Style.blackTextArea(ymlPropertiesForm.getPropertiesTextArea());
        Style.blackTextArea(ymlPropertiesForm.getYmlTextArea());
        Style.blackTextArea(ymlPropertiesForm.getYamlValidateInputTextArea());
        Style.blackTextArea(ymlPropertiesForm.getYamlValidateResultTextArea());

        ymlPropertiesForm.getYmlPropertiesPanel().updateUI();
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        ymlPropertiesPanel = new JPanel();
        ymlPropertiesPanel.setLayout(new GridLayoutManager(1, 1, new Insets(10, 0, 0, 0), -1, -1));
        ymlPropertiesPanel.setMinimumSize(new Dimension(400, 300));
        ymlPropertiesPanel.setPreferredSize(new Dimension(400, 300));
        tabbedPane1 = new JTabbedPane();
        ymlPropertiesPanel.add(tabbedPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 3, new Insets(10, 10, 10, 10), -1, -1));
        tabbedPane1.addTab("yml/properties", panel1);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, 1, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        properties2ymlButton = new JButton();
        properties2ymlButton.setText("properties → yml");
        panel2.add(properties2ymlButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        yml2propertiesButton = new JButton();
        yml2propertiesButton.setText("properties ← yml");
        panel2.add(yml2propertiesButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel2.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel2.add(spacer2, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setHorizontalScrollBarPolicy(31);
        panel3.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        propertiesTextArea = new JTextArea();
        propertiesTextArea.setLineWrap(true);
        propertiesTextArea.setWrapStyleWord(true);
        scrollPane1.setViewportView(propertiesTextArea);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel4, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JScrollPane scrollPane2 = new JScrollPane();
        scrollPane2.setHorizontalScrollBarPolicy(31);
        panel4.add(scrollPane2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        ymlTextArea = new JTextArea();
        ymlTextArea.setLineWrap(true);
        ymlTextArea.setWrapStyleWord(true);
        scrollPane2.setViewportView(ymlTextArea);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridLayoutManager(3, 1, new Insets(10, 10, 10, 10), -1, -1));
        tabbedPane1.addTab("YAML校验", panel5);
        final JScrollPane scrollPane3 = new JScrollPane();
        scrollPane3.setHorizontalScrollBarPolicy(31);
        panel5.add(scrollPane3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        yamlValidateInputTextArea = new JTextArea();
        yamlValidateInputTextArea.setLineWrap(true);
        yamlValidateInputTextArea.setWrapStyleWord(true);
        scrollPane3.setViewportView(yamlValidateInputTextArea);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel5.add(panel6, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        yamlValidateButton = new JButton();
        yamlValidateButton.setText("校验");
        panel6.add(yamlValidateButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        yamlFormatButton = new JButton();
        yamlFormatButton.setText("格式化");
        panel6.add(yamlFormatButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane4 = new JScrollPane();
        scrollPane4.setHorizontalScrollBarPolicy(31);
        panel5.add(scrollPane4, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(-1, 120), null, 0, false));
        yamlValidateResultTextArea = new JTextArea();
        yamlValidateResultTextArea.setEditable(false);
        yamlValidateResultTextArea.setLineWrap(true);
        yamlValidateResultTextArea.setWrapStyleWord(true);
        scrollPane4.setViewportView(yamlValidateResultTextArea);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return ymlPropertiesPanel;
    }

}
