[versions]
kotlin = "2.2.21"
composeMultiplatform = "1.12.0"
coroutines = "1.10.2"
serialization = "1.8.1"
jackson = "2.18.3"
jsonPath = "2.9.0"
sqlite = "3.49.1.0"
rsyntaxtextarea = "3.6.0"
slf4j = "2.0.17"
junit = "4.13.2"
uapJava = "1.6.1"
cronUtils = "9.2.1"
javaDiffUtils = "4.15"
javaParser = "3.26.4"
jsoup = "1.18.3"
snakeyaml = "2.3"

[libraries]
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
compose-material = { module = "org.jetbrains.compose.material:material", version.ref = "composeMultiplatform" }
compose-desktop = { module = "org.jetbrains.compose.desktop:desktop", version.ref = "composeMultiplatform" }
compose-desktop-macos-x64 = { module = "org.jetbrains.compose.desktop:desktop-jvm-macos-x64", version.ref = "composeMultiplatform" }
compose-desktop-macos-arm64 = { module = "org.jetbrains.compose.desktop:desktop-jvm-macos-arm64", version.ref = "composeMultiplatform" }
compose-desktop-windows-x64 = { module = "org.jetbrains.compose.desktop:desktop-jvm-windows-x64", version.ref = "composeMultiplatform" }
compose-desktop-linux-x64 = { module = "org.jetbrains.compose.desktop:desktop-jvm-linux-x64", version.ref = "composeMultiplatform" }
compose-ui-test-junit4 = { module = "org.jetbrains.compose.ui:ui-test-junit4", version.ref = "composeMultiplatform" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
json-path = { module = "com.jayway.jsonpath:json-path", version.ref = "jsonPath" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
rsyntaxtextarea = { module = "com.fifesoft:rsyntaxtextarea", version.ref = "rsyntaxtextarea" }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" }
uap-java = { module = "com.github.ua-parser:uap-java", version.ref = "uapJava" }
cron-utils = { module = "com.cronutils:cron-utils", version.ref = "cronUtils" }
java-diff-utils = { module = "io.github.java-diff-utils:java-diff-utils", version.ref = "javaDiffUtils" }
javaparser-core = { module = "com.github.javaparser:javaparser-core", version.ref = "javaParser" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
