import { _electron as electron, expect, test } from '@playwright/test'
import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

test('Java regex highlighting, navigation, favorites and AES compatibility', async () => {
  const directory = await mkdtemp(join(tmpdir(), 'mootool-regex-crypto-'))
  const app = await electron.launch({ args: ['.', `--user-data-dir=${directory}`], cwd: process.cwd(), env: { ...process.env, NODE_ENV: 'test', MOOTOOL_TOOL_VIEWS: '0' } })
  try {
    const page = await app.firstWindow()
    await page.locator('.tool-button').filter({ hasText: '正则' }).click()
    const tabs = page.locator('.regex-workspace .tool-tabs')
    await expect.poll(() => tabs.evaluate(element => element.scrollHeight - element.clientHeight)).toBe(0)
    await page.getByRole('textbox', { name: '待匹配文本', exact: true }).fill('foo.bar fooXbar foo.bar')
    await page.locator('#regex-expression').fill('\\Qfoo.bar\\E')
    await expect(page.locator('.regex-results article')).toHaveCount(2)
    await expect(page.locator('.regex-match-highlight')).toHaveCount(2)
    await page.getByRole('button', { name: '下一个匹配', exact: true }).click()
    await expect(page.getByRole('textbox', { name: '待匹配文本', exact: true })).toBeFocused()
    await page.getByRole('button', { name: '收藏夹', exact: true }).click()
    const dialog = page.getByRole('dialog')
    await dialog.getByRole('textbox', { name: '名称', exact: true }).fill('Literal')
    await dialog.getByRole('button', { name: '保存', exact: true }).click()
    await dialog.getByRole('button', { name: '编辑', exact: true }).click()
    await dialog.getByRole('textbox', { name: '名称', exact: true }).fill('Literal renamed')
    await dialog.getByRole('button', { name: '保存', exact: true }).click()
    await dialog.locator('.favorite-item > button').first().click()
    await page.getByRole('combobox', { name: '正则引擎' }).selectOption('javascript')
    await expect(page.locator('.regex-results article')).toHaveCount(0)
    await page.locator('#regex-expression').fill('foo\\.bar')
    await expect(page.locator('.regex-results article')).toHaveCount(2)
    await page.locator('#regex-expression').fill('(a+)+$')
    await page.getByRole('textbox', { name: '待匹配文本', exact: true }).fill('a'.repeat(40) + '!')
    await expect(page.locator('.regex-results')).toContainText('匹配超时')
    await page.locator('#regex-expression').fill('foo\\.bar')
    await page.getByRole('textbox', { name: '待匹配文本', exact: true }).fill('foo.bar fooXbar foo.bar')
    await expect(page.locator('.regex-results article')).toHaveCount(2)
    await page.screenshot({ path: 'test-results/regex-java-parity.png', fullPage: true })
    await page.reload()
    await page.locator('.tool-button').filter({ hasText: '正则' }).click()
    await expect(page.locator('#regex-expression')).toHaveValue('foo\\.bar')
    await expect(page.getByRole('combobox', { name: '正则引擎' })).toHaveValue('javascript')
    await page.locator('.tool-button').filter({ hasText: '加解密/随机' }).click()
    await page.locator('.compact-field--grow input').fill('123456789012345678901234')
    await page.getByRole('textbox', { name: '明文', exact: true }).fill('MooTool parity')
    await page.getByRole('button', { name: '加密', exact: true }).click()
    await expect(page.getByRole('textbox', { name: '密文', exact: true })).toHaveText('a66c2ff48c6ded0ae657017c86bc4930')
    await page.getByRole('textbox', { name: '密文', exact: true }).fill('3f4916b141b6d3442df1017170f155e8')
    await page.getByRole('checkbox', { name: '旧 Electron 密钥处理（仅解密）' }).check()
    await page.getByRole('button', { name: '解密', exact: true }).click()
    await expect(page.getByRole('textbox', { name: '明文', exact: true })).toHaveText('MooTool parity')
  } finally { await app.close(); await rm(directory, { recursive: true, force: true }) }
})
