include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false

analyzer:
  exclude:
    - build/**
    - windows/**
    - macos/**
    - linux/**
  errors:
    curly_braces_in_flow_control_structures: ignore
