name: mootool_next_flutter
description: Independent MooTool Next Flutter desktop toolbox.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_selector: ^1.0.3
  path: ^1.9.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/brand/mootool-logo.png
    - assets/brand/wx-zanshang.jpg
