import { CheckCircle2, CircleAlert, Eraser, Play, RefreshCw, Square, TriangleAlert } from 'lucide-react'
import { useEffect, useMemo, useRef, useState } from 'react'
import { useLocalizedMessages, type LocalizedMessageKey, type MessageValues } from '../../app/localizedMessages'
import { CodeEditor } from '../../shared/CodeEditor'
import { contentFingerprint } from '../../shared/fingerprint'
import { codeRuntimeApi } from '../../platform/api/codeRuntimeApi'
import type { CodeRunResult, CodeRuntimeId, CodeRuntimeStatus } from '../../platform/contracts/codeRuntime'
import { useToolSessionReport } from '../toolWebview/useToolSessionReport'
import { useOperationHistory } from '../history/useOperationHistory'
import { runtimeMessages } from './runtimeMessages'
import { parseRuntimeArguments, RuntimeToolError } from './runtimeTools'

type RuntimeMessageKey = LocalizedMessageKey<typeof runtimeMessages>
type RuntimeNotice = { key: RuntimeMessageKey; values?: MessageValues } | { raw: string }

const samples: Record<CodeRuntimeId, string> = {
  java: 'public class Main {\n  public static void main(String[] args) {\n    System.out.println("Hello from MooTool Tauri");\n  }\n}',
  groovy: `['Java', 'Python', 'Node.js'].eachWithIndex { item, i -> println "\${i + 1}. \${item}" }`,
  python: 'tools = ["Java", "Python", "Node.js"]\nfor index, tool in enumerate(tools, 1):\n    print(f"{index}. {tool}")',
  node: "const tools = ['Java', 'Python', 'Node.js']\ntools.forEach((tool, index) => console.log(`${index + 1}. ${tool}`))"
}

export function RuntimeSurface() {
  const { t } = useLocalizedMessages(runtimeMessages)
  const [runtime, setRuntime] = useState<CodeRuntimeId>('node'); const [codes, setCodes] = useState(samples); const [statuses, setStatuses] = useState<CodeRuntimeStatus[]>([]); const [argumentsText, setArgumentsText] = useState(''); const [workingDirectory, setWorkingDirectory] = useState(''); const [stdout, setStdout] = useState(''); const [stderr, setStderr] = useState(''); const [running, setRunning] = useState(false); const [requestId, setRequestId] = useState(''); const [result, setResult] = useState<CodeRunResult>(); const [notice, setNotice] = useState<RuntimeNotice>({ key: 'notice.detecting' }); const [failed, setFailed] = useState(false); const stdoutRef = useRef(''); const stderrRef = useRef(''); const code = codes[runtime]; const status = statuses.find((item) => item.id === runtime)
  const noticeText = 'raw' in notice ? notice.raw : t(notice.key, notice.values)
  const session = useMemo(() => ({ digest: JSON.stringify({ runtime, codeHash: contentFingerprint(code), running, exitCode: result?.exitCode }), summary: `${runtimeName(runtime)} · ${running ? t('session.running') : result ? t('session.exit', { code: result.exitCode ?? '-' }) : status?.available ? t('session.available') : t('session.missing')}` }), [code, result, running, runtime, status, t])
  const { sessionId, reportError } = useToolSessionReport('runtime', session.digest, session.summary)
  const recordOperation = useOperationHistory('runtime')
  useEffect(() => { void detect() }, [])
  useEffect(() => { const listener = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key === 'Enter' && !running) { event.preventDefault(); void run() } }; addEventListener('keydown', listener); return () => removeEventListener('keydown', listener) })
  async function detect() { try { const loaded = await codeRuntimeApi.detect(); setStatuses(loaded); setNotice({ key: 'notice.detected', values: { count: loaded.filter((item) => item.available).length } }); setFailed(false) } catch (cause) { fail(cause) } }
  async function run() { if (running) return; if (status && !status.available) { setNotice({ key: 'error.runtimeMissing', values: { runtime: runtimeName(runtime) } }); setFailed(true); return } let args: string[]; try { args = parseRuntimeArguments(argumentsText) } catch (cause) { return fail(cause) } const id = crypto.randomUUID(); setRequestId(id); setRunning(true); setResult(undefined); stdoutRef.current = ''; stderrRef.current = ''; setStdout(''); setStderr(''); setFailed(false); try { const completed = await codeRuntimeApi.run({ requestId: id, runtime, code, timeoutMs: 30_000, arguments: args, workingDirectory }, (event) => { if (event.stream === 'stdout') { stdoutRef.current += event.text; setStdout(stdoutRef.current) } else { stderrRef.current += event.text; setStderr(stderrRef.current) } }); setResult(completed); setStdout(completed.stdout); setStderr(completed.stderr); setNotice(completed.timedOut ? { key: 'notice.timeout' } : completed.cancelled ? { key: 'notice.cancelled' } : { key: 'notice.finished', values: { code: completed.exitCode ?? '-' } }); setFailed(completed.exitCode !== 0); recordOperation(t('operation.run'), `${runtimeName(runtime)} · exit ${completed.exitCode ?? '-'} · ${completed.durationMs} ms`, completed.exitCode === 0 ? 'success' : 'error') } catch (cause) { fail(cause); recordOperation(t('operation.run'), `${runtimeName(runtime)} · ${runtimeErrorText(cause, t)}`, 'error') } finally { setRunning(false); setRequestId('') } }
  async function stop() { if (requestId) { await codeRuntimeApi.cancel(requestId); setNotice({ key: 'notice.stopping' }) } }
  function fail(cause: unknown) { setNotice(cause instanceof RuntimeToolError ? { key: `error.${cause.code}` } : { raw: cause instanceof Error ? cause.message : String(cause) }); setFailed(true) }
  return <main className="utility-workbench code-runtime-workbench"><header className="utility-header"><div><span className="eyebrow">TAURI CONTROLLED CODE RUNNER</span><h1>{t('title')}</h1></div><span className="utility-session">{t('session.label')} <code>{sessionId}</code></span></header>
    <section className="code-runtime-toolbar"><div className="utility-segments">{(['java','groovy','python','node'] as const).map((item) => <button className={runtime === item ? 'utility-segment utility-segment--active' : 'utility-segment'} type="button" disabled={running} key={item} onClick={() => setRuntime(item)}>{runtimeName(item)}<i className={statuses.find((entry) => entry.id === item)?.available ? 'runtime-dot runtime-dot--ok' : 'runtime-dot'} /></button>)}</div><label>{t('field.arguments')}<input value={argumentsText} placeholder="--name 'Moo Tool'" onChange={(event) => setArgumentsText(event.target.value)} /></label><label>{t('field.workingDirectory')}<input value={workingDirectory} placeholder={t('placeholder.workingDirectory')} onChange={(event) => setWorkingDirectory(event.target.value)} /></label><button className="secondary-button" type="button" disabled={running} onClick={() => void detect()}><RefreshCw />{t('action.detect')}</button>{running ? <button className="primary-button runtime-stop" type="button" onClick={() => void stop()}><Square />{t('action.stop')}</button> : <button className="primary-button" type="button" onClick={() => void run()}><Play />{t('action.run')}</button>}</section>
    {status && <section className={status.available ? 'runtime-status-line runtime-status-line--ok' : 'runtime-status-line'}>{status.available ? <CheckCircle2 /> : <CircleAlert />}<strong>{runtimeName(runtime)}</strong><code>{status.command}</code><span>{status.version || t('status.notInstalled')}</span></section>}
    <section className="code-runtime-layout"><section className="utility-editor-card"><header><span>{t('pane.source', { runtime: runtimeName(runtime) })}</span><button className="utility-copy" type="button" onClick={() => setCodes({ ...codes, [runtime]: samples[runtime] })}><Eraser />{t('action.restore')}</button></header><CodeEditor ariaLabel={t('aria.source')} value={code} onChange={(value) => setCodes({ ...codes, [runtime]: value })} className="utility-code-editor" lineWrapping={false} /></section><section className="runtime-output-card"><header><strong>{t('pane.output')}</strong>{result && <span>{result.durationMs} ms · exit {result.exitCode ?? '-'}</span>}</header><div>{stdout && <pre className="runtime-stdout">{stdout}</pre>}{stderr && <pre className="runtime-stderr">{stderr}</pre>}{!stdout && !stderr && <p>{t(running ? 'output.running' : 'output.empty')}</p>}</div>{result && <footer title={result.command}><code>{result.command}</code></footer>}</section></section>
    <footer className={failed ? 'utility-status utility-status--error' : 'utility-status'}><span>{failed ? <TriangleAlert /> : <CheckCircle2 />}{noticeText}</span><span>{t('footer.capabilities')}</span><code>{session.summary}</code></footer>{reportError && <p className="tool-surface-report-error">{t('report.error', { error: reportError })}</p>}</main>
}
function runtimeName(value: CodeRuntimeId) { return { java: 'Java', groovy: 'Groovy', python: 'Python', node: 'Node.js' }[value] }
function runtimeErrorText(cause: unknown, t: (key: RuntimeMessageKey) => string): string { return cause instanceof RuntimeToolError ? t(`error.${cause.code}`) : cause instanceof Error ? cause.message : String(cause) }
