# Japanese translations for README (same Chinese keys as EN_MAP in build_readme_i18n.py)

ZH_JA_MAP: list[tuple[str, str]] = [
    ("## 关于",
     "## About"),
    ("你好！感谢使用 MooTool。「Moo」是我女儿的小名。",
     "MooTool をご利用いただきありがとうございます。「Moo」は作者の娘の愛称です。"),
    ("我持续构建和改进 MooTool，来支撑自己的日常开发工作。",
     "自分の日常の開発作業を支えるために、MooTool を作り続け、改善し続けています。"),
    ("现在用 Swing 做项目的 Java 开发者越来越少了，但我依然热爱它。所以每当有一点空闲时间，我都会投入到开发中。最终做出了一些成果，尽管网上已有很多类似工具。",
     "Swing で開発する Java 開発者は減りましたが、今でもその開発を楽しんでいます。空いた時間を少しずつ、このプロジェクトの開発に注いできました。Web 上に似たツールが多くある中でも、ひとつの形にすることができました。"),
    ("希望你使用它的愉快程度，不亚于我开发它时的投入。",
     "開発したときと同じくらい、楽しく使っていただければ幸いです。"),
    ("Windows • Linux • macOS。各产品的目标平台与当前状态见下表；开发中的版本尚未完成全部目标平台的发行验收。",
     "Windows • Linux • macOS。各製品の対象プラットフォームと現在の状況は下表をご覧ください。開発中の製品は、すべての対象プラットフォームでのリリース受け入れ確認を完了していません。"),
    ("## 产品线",
     "## 製品ライン"),
    ("MooTool 目前包含 7 条独立产品线，各自维护代码、构建、版本、安装身份、数据和更新通道，可并行安装与独立演进。不同产品的版本号不作横向比较，功能覆盖以各自文档为准。",
     "MooTool には現在 7 つの独立した製品ラインがあり、コード、ビルド、バージョン、インストール識別子、データ、更新チャネルを個別に管理しています。並行してインストールでき、それぞれ独立して開発を進めています。製品間でバージョン番号を比較せず、機能の対応状況は各製品のドキュメントをご確認ください。"),
    ("| 产品 / 源码 | 技术与介绍 | 目标平台 | 当前状态 / 下载 |",
     "| 製品 / ソース | 技術と概要 | 対象プラットフォーム | 状況 / ダウンロード |"),
    ("| [**MooTool Next Electron**](next/README.md) | Electron、Vite、React、TypeScript；当前推荐的主力桌面版本。 | Windows / Linux / macOS | 稳定版：[下载 1.1.4](https://github.com/rememberber/MooTool/releases/tag/next-electron-v1.1.4) |",
     "| [**MooTool Next Electron**](next/README.md) | Electron、Vite、React、TypeScript。現在推奨する主力デスクトップ版。 | Windows / Linux / macOS | 安定版：[1.1.4 をダウンロード](https://github.com/rememberber/MooTool/releases/tag/next-electron-v1.1.4) |"),
    ("| [**MooTool Java**](src/) | Java、Swing；持续维护的原始桌面版本。 | Windows / Linux / macOS | 稳定版：[下载 1.8.6](https://github.com/rememberber/MooTool/releases/tag/v1.8.6) · [Gitee 镜像](https://gitee.com/zhoubochina/MooTool/releases) |",
     "| [**MooTool Java**](src/) | Java、Swing。保守を継続している従来のデスクトップ版。 | Windows / Linux / macOS | 安定版：[1.8.6 をダウンロード](https://github.com/rememberber/MooTool/releases/tag/v1.8.6) · [Gitee ミラー](https://gitee.com/zhoubochina/MooTool/releases) |"),
    ("| [**MooTool Next Tauri**](next-tauri/README.md) | Tauri 2、Rust、React、TypeScript；已实现 25 个工具、独立存储与更新。 | Windows / Linux / macOS | 候选预发布版：[下载 0.1.0-rc.2](https://github.com/rememberber/MooTool/releases/tag/next-tauri-v0.1.0-rc.2) |",
     "| [**MooTool Next Tauri**](next-tauri/README.md) | Tauri 2、Rust、React、TypeScript。25 個のツールと独立したデータ保存・更新を実装。 | Windows / Linux / macOS | リリース候補版：[0.1.0-rc.2 をダウンロード](https://github.com/rememberber/MooTool/releases/tag/next-tauri-v0.1.0-rc.2) |"),
    ("| [**MooTool Next macOS Native**](next-macos-native/README.md) | SwiftUI、AppKit、系统框架；原生工作区、JSON 文档库、随手记与图片附件。 | macOS 14+ | 0.6.0 开发版；可从源码构建 `.app` / DMG。 |",
     "| [**MooTool Next macOS Native**](next-macos-native/README.md) | SwiftUI、AppKit、システムフレームワーク。ネイティブワークスペース、JSON ライブラリ、クイックメモ、画像添付。 | macOS 14+ | 0.6.0 開発版。ソースから `.app` / DMG をビルド可能。 |"),
    ("| [**MooTool Next Flutter**](next-flutter/README.md) | Flutter、Dart；工具与桌面通道已实现，平台验收和部分能力仍在完善。 | Windows / Linux / macOS | 0.1.0 开发版；提供本地运行与未签名打包脚本。 |",
     "| [**MooTool Next Flutter**](next-flutter/README.md) | Flutter、Dart。ツールとデスクトップチャネルを実装済み。プラットフォーム検証と一部機能は対応中。 | Windows / Linux / macOS | 0.1.0 開発版。ローカル実行・未署名パッケージ作成スクリプトあり。 |"),
    ("| [**MooTool Next Compose**](next-compose/README.md) | Kotlin、Compose Multiplatform Desktop；已实现多项工具、随手记及备份恢复。 | Windows / Linux / macOS | 0.1.0 开发版；已验证本机 macOS app-image 构建，自带 JVM 运行时。 |",
     "| [**MooTool Next Compose**](next-compose/README.md) | Kotlin、Compose Multiplatform Desktop。複数のツール、クイックメモ、バックアップ・復元を実装。 | Windows / Linux / macOS | 0.1.0 開発版。JVM 同梱の macOS app-image をローカルでビルド確認済み。 |"),
    ("| [**MooTool Next FX**](next-fx/README.md) | OpenJDK、OpenJFX（JavaFX）；已有应用壳、JSON 文档库、编码解码和正则工具。 | Windows / Linux / macOS | 0.1.0-SNAPSHOT 早期开发版；已实现本机 macOS app-image 打包。 |",
     "| [**MooTool Next FX**](next-fx/README.md) | OpenJDK、OpenJFX（JavaFX）。アプリシェル、JSON ライブラリ、エンコード・デコード、正規表現ツールを実装。 | Windows / Linux / macOS | 0.1.0-SNAPSHOT 初期開発版。ローカルでの macOS app-image 作成に対応。 |"),
    ("点击产品名查看源码或产品 README；各产品 README 提供开发环境、运行、打包和验收说明。当前 macOS 原生产品位于 `next-macos-native/`，`macos/` 是早期 SwiftUI 原型。",
     "製品名のリンクからソースまたは製品 README を開けます。各 README に開発環境、実行、パッケージ作成、検証の説明があります。現在の macOS ネイティブ製品は `next-macos-native/` にあり、`macos/` は初期の SwiftUI プロトタイプです。"),
    ("> 以下截图来自 MooTool Java；其他产品的界面与验收记录请查看各自 README。",
     "> 以下は MooTool Java のスクリーンショットです。他の製品の画面と検証記録は各 README をご覧ください。"),
    ("- [MooTool Next Tauri 0.1.0-rc.2（候选预发布版）](https://github.com/rememberber/MooTool/releases/tag/next-tauri-v0.1.0-rc.2)",
     "- [MooTool Next Tauri 0.1.0-rc.2（リリース候補版）](https://github.com/rememberber/MooTool/releases/tag/next-tauri-v0.1.0-rc.2)"),
    ("macOS Native、Flutter、Compose 和 FX 当前提供源码构建入口，详见上方产品表中的 README。开发版本号不代表已提供公开稳定安装包。",
     "macOS Native、Flutter、Compose、FX のソースビルドについては、上の製品表にある README をご覧ください。開発版のバージョン番号は、公開安定版のインストーラーがあることを意味しません。"),
    ("> 以下为 MooTool Java 的功能地图；其他产品的已实现功能、差异和待办请查看各自文档。",
     "> 以下は MooTool Java の機能一覧です。他の製品の実装済み機能、差異、今後の予定は各ドキュメントをご覧ください。"),
    ("各产品使用独立工程，请先阅读上方产品表链接的 README，并在对应目录开发。以下 JDK、IntelliJ IDEA、Maven 和打包说明仅适用于仓库根目录的 MooTool Java。",
     "各製品は独立したプロジェクトです。製品表の README を読み、対応するディレクトリで開発してください。以下の JDK、IntelliJ IDEA、Maven、パッケージ作成の説明は、リポジトリ直下の MooTool Java にのみ適用されます。"),
    ("Handy tool set for developers.   \n开发者常备小工具", "開発者向けデスクトップツールセット"),
    ("## 支持的平台", "## 対応プラットフォーム"),
    ("## 截图速览", "## スクリーンショット"),
    ("> 以下为主要功能界面截图。翻译、UA分析、图片助手、PDF、环境变量、系统信息、配置文件转换、Protobuf 等模块暂未单独配图，可在安装后于对应 Tab 中体验。",
     "> 主要機能のスクリーンショットは以下の通りです。翻訳、UA 分析、画像アシスタント、PDF、環境変数、システム情報、設定ファイル変換、Protobuf などのモジュールは個別の画像がありません。インストール後、該当タブでお試しください。"),
    ("![随手记-快捷替换]", "![クイックメモ - クイック置換]"),
    ("![随手记]", "![クイックメモ]"),
    ("![主题与外观]", "![テーマと外観]"),
    ("## 下载", "## ダウンロード"),
    ("- [MooTool Next Electron 1.1.4（推荐）](https://github.com/rememberber/MooTool/releases/tag/next-electron-v1.1.4)",
     "- [MooTool Next Electron 1.1.4（推奨）](https://github.com/rememberber/MooTool/releases/tag/next-electron-v1.1.4)"),
    ("- [MooTool Java 1.7.9](https://github.com/rememberber/MooTool/releases/tag/v1.7.9)",
     "- [MooTool Java 1.7.9](https://github.com/rememberber/MooTool/releases/tag/v1.7.9)"),
    ("- [全部 GitHub Releases](https://github.com/rememberber/MooTool/releases)",
     "- [GitHub Releases 一覧](https://github.com/rememberber/MooTool/releases)"),
    ("- [MooTool Java Gitee Releases](https://gitee.com/zhoubochina/MooTool/releases)",
     "- [Gitee の MooTool Java Releases](https://gitee.com/zhoubochina/MooTool/releases)"),
    ("## 鼓励/赞赏", "## 支援 / スポンサー"),
    ("**如果MooTool项目对您有所帮助或带来便利，  \n欢迎对我每天下班和周末时光的努力进行肯定，  \n您的赞赏将会给我带来更多动力**",
     "**MooTool がお役に立った場合は、日々の仕事終わりや週末に費やした開発への支援をご検討ください。皆さまの応援が励みになります。**"),
    ("# MooTool全功能地图", "# MooTool 機能一覧"),
    ("> 多个工具模块提供统一的「历史记录」子 Tab，支持搜索、应用、复制输入/输出、删除与清空。",
     "> 多くのモジュールに **履歴** サブタブがあり、検索・適用・入出力のコピー・削除・全消去に対応しています。"),
    ("## 随手记", "## クイックメモ"),
    ("### 多语言语法高亮支持", "### 多言語シンタックスハイライト"),
    ("### 常见语言代码格式化", "### 主要言語のコード整形"),
    ("### 有序/无序列表", "### 番号付き / 箇条書きリスト"),
    ("### Markdown 实时预览", "### Markdown リアルタイムプレビュー"),
    ("### Markdown 插入图片", "### Markdown への画像挿入"),
    ("### 导出/批量导出，搜索与全局查找", "### エクスポート / 一括エクスポート、検索、全体検索"),
    ("### 文档信息（创建/更新时间、字数等）", "### ドキュメント情報（作成/更新日時、文字数など）"),
    ("### 超链接识别与点击跳转", "### リンク検出とクリックで開く"),
    ("### 字体、字号、列表颜色", "### フォント、サイズ、リストの色"),
    ("### 快捷替换面板", "### クイック置換パネル"),
    ("侧栏集中提供以下批量文本操作，支持仅处理选中行：", "サイドパネルで以下の一括テキスト操作（選択行のみも可）："),
    ("- 自动保存", "- 自動保存"),
    ("- 去掉空格", "- 空白を削除"),
    ("- 去掉空行", "- 空行を削除"),
    ("- 去掉Tab(\\t)", "- タブ (\\t) を削除"),
    ("- 科学计数法->普通数字", "- 指数表記 → 通常の数値"),
    ("- 普通数字->科学计数法", "- 通常の数値 → 指数表記"),
    ("- 普通数字->千分位", "- 通常の数値 → 桁区切り"),
    ("- 千分位->普通数字", "- 桁区切り → 通常の数値"),
    ("- 下划线命名->驼峰命名", "- snake_case → camelCase"),
    ("- 驼峰命名->下划线命名", "- camelCase → snake_case"),
    ("- 大写->小写", "- 大文字 → 小文字"),
    ("- 小写->大写", "- 小文字 → 大文字"),
    ("- 去掉换行", "- 改行を削除"),
    ("- 换行->,", "- 改行 → カンマ"),
    ("- 换行->','", "- 改行 → ','"),
    ("- 换行->\",\"", "- 改行 → \",\""),
    ("- ,->换行", "- カンマ → 改行"),
    ("- ','->换行", "- ',' → 改行"),
    ("- \",\"->换行", "- \",\" → 改行"),
    ("- Tab(\\t)->换行", "- タブ (\\t) → 改行"),
    ("- 按行去重并统计出现次数", "- 行単位で重複削除し出現回数を集計"),
    ("- 按行去重", "- 行単位で重複削除"),
    ("- 转义", "- エスケープ"),
    ("- 反转义", "- アンエスケープ"),
    ("- 按行倒序", "- 行を逆順に"),
    ("- 按行A->Z排序", "- 行を A→Z でソート"),
    ("- 按行Z->A排序", "- 行を Z→A でソート"),
    ("- 按拼音排序", "- ピンイン順でソート"),
    ("## 时间转换", "## 時刻変換"),
    ("### 时间戳转换", "### タイムスタンプ変換"),
    ("- 时间->时间戳(毫秒)", "- 日時 → タイムスタンプ（ミリ秒）"),
    ("- 时间戳(毫秒)->时间", "- タイムスタンプ（ミリ秒）→ 日時"),
    ("- 时间戳->时间(秒)", "- タイムスタンプ（秒）→ 日時"),
    ("- 时间->时间戳(秒)", "- 日時 → タイムスタンプ（秒）"),
    ("### 历史记录", "### 履歴"),
    ("### 大屏时钟", "### フルスクリーン時計"),
    ("### 时区选择与快捷时区", "### タイムゾーン選択とショートカット"),
    ("## JSON", "## JSON"),
    ("### JSON格式化", "### JSON 整形"),
    ("- Key 按字母顺序排序", "- キーをアルファベット順にソート"),
    ("- 忽略 key 大小写", "- キーの大文字小文字を無視"),
    ("- 检查重复 key", "- 重複キーをチェック"),
    ("### JSON压缩", "### JSON 圧縮"),
    ("### 导出/批量导出，查找", "### エクスポート / 一括エクスポート、検索"),
    ("### 字体、字号", "### フォントとサイズ"),
    ("### JSON Key Value互转", "### JSON キーと値の入れ替え"),
    ("### JSON转XML", "### JSON → XML"),
    ("### XML转JSON", "### XML → JSON"),
    ("### JavaBean转JSON", "### JavaBean → JSON"),
    ("### JSON转JavaBean", "### JSON → JavaBean"),
    ("### 转义", "### エスケープ"),
    ("### 反转义", "### アンエスケープ"),
    ("### 通过JsonPath获取JSON数据", "### JSON Path で JSON データを取得"),
    ("### 可视化获取JsonPath", "### JSON Path をビジュアル選択"),
    ("## 翻译", "## 翻訳"),
    ("### 多语言互译（中/英/日/韩/法/西/德/俄等 20+ 语言，支持自动检测）",
     "### 20 以上の言語を相互翻訳（中/英/日/韓/仏/西/独/露など、自動検出対応）"),
    ("### Google / Bing 翻译源，失败时自动降级", "### Google / Bing 翻訳（失敗時に自動フォールバック）"),
    ("### 收藏到单词本", "### 単語帳に保存"),
    ("### 单词本", "### 単語帳"),
    ("- 搜索、新建、编辑、删除", "- 検索、新規、編集、削除"),
    ("- 重新翻译", "- 再翻訳"),
    ("### 翻译历史记录", "### 翻訳履歴"),
    ("## Host", "## Host"),
    ("### Host格式化/语法高亮", "### Host 整形 / シンタックスハイライト"),
    ("### 本机Host管理/查看", "### システム hosts の管理 / 表示"),
    ("### Host导入/导出", "### Host のインポート / エクスポート"),
    ("### 搜索与查找/替换", "### 検索、検索と置換"),
    ("## HTTP", "## HTTP"),
    ("### HTTP请求，支持GET/POST/PUT/DELETE/HEAD/PATCH/OPTIONS", "### HTTP リクエスト（GET/POST/PUT/DELETE/HEAD/PATCH/OPTIONS）"),
    ("### cURL 导入", "### cURL インポート"),
    ("### HTTP Header/Body格式化", "### HTTP ヘッダー / ボディの整形"),
    ("### 请求管理", "### リクエスト管理"),
    ("### 请求历史记录", "### リクエスト履歴"),
    ("### 搜索", "### 検索"),
    ("## UA分析", "## UA 分析"),
    ("### User-Agent 解析（浏览器、引擎、操作系统、设备类型/品牌/型号等）",
     "### User-Agent 解析（ブラウザ、エンジン、OS、デバイスタイプ/ブランド/モデルなど）"),
    ("### 识别移动端 / 爬虫 Bot", "### モバイル / Bot クローラーの検出"),
    ("### 预设 UA 快速选择（Chrome、Firefox、Safari、Edge、微信内置浏览器、curl 等）",
     "### プリセット UA（Chrome、Firefox、Safari、Edge、WeChat 内蔵ブラウザ、curl など）"),
    ("### 粘贴 / 清空", "### 貼り付け / クリア"),
    ("## 编码转换", "## エンコード / デコード"),
    ("### Native->Unicode", "### Native → Unicode"),
    ("### Unicode->Native", "### Unicode → Native"),
    ("### URL编码/解码", "### URL エンコード / デコード"),
    ("### Native->十六进制", "### Native → 16 進数"),
    ("### 十六进制->Native", "### 16 進数 → Native"),
    ("### Native->ASCII（十进制/十六进制字符码）", "### Native → ASCII（10/16 進コードポイント）"),
    ("### ASCII->Native", "### ASCII → Native"),
    ("## 二维码", "## QR コード"),
    ("### 二维码生成", "### QR コード生成"),
    ("- 尺寸自定义", "- サイズをカスタム"),
    ("- 纠错等级自定义", "- 誤り訂正レベルをカスタム"),
    ("- logo自定义", "- ロゴをカスタム"),
    ("### 二维码解析", "### QR コード解析"),
    ("### 从剪贴板识别", "### クリップボードから読み取り"),
    ("## 加解密/随机", "## 暗号化 / ランダム"),
    ("> 支持国密 SM2 / SM3 / SM4", "> 中国国密 SM2 / SM3 / SM4 に対応"),
    ("### 对称加密/解密", "### 対称暗号の暗号化 / 復号"),
    ("### 非对称加密/解密", "### 非対称暗号の暗号化 / 復号"),
    ("- SM2（加密/解密、私钥签名、公钥验签）", "- SM2（暗号化/復号、秘密鍵署名、公開鍵検証）"),
    ("### 摘要算法（文件/文本摘要）", "### ダイジェスト（ファイル / テキスト）"),
    ("### Base64编码/解码", "### Base64 エンコード / デコード"),
    ("### Base32编码/解码", "### Base32 エンコード / デコード"),
    ("### 随机UUID生成", "### ランダム UUID 生成"),
    ("### 随机生成只包含数字/字母/数字字母的字符串，位数自定义", "### 数字 / 英字 / 英数字のランダム文字列（桁数指定）"),
    ("### 随机生成复杂密码，位数自定义", "### 複雑なランダムパスワード（桁数指定）"),
    ("## 计算", "## 電卓"),
    ("### 四则运算", "### 四則演算"),
    ("### 进制转换", "### 進数変換"),
    ("### 最大公约数", "### 最大公約数"),
    ("### 最小公倍数", "### 最小公倍数"),
    ("### 排列组合数", "### 順列と組み合わせ"),
    ("## 网络/IP", "## ネットワーク / IP"),
    ("### IP查询", "### IP 検索"),
    ("### 域名查询", "### ドメイン検索"),
    ("### ipv4-Long互相转换", "### IPv4 ↔ long 変換"),
    ("### WHOIS 查询", "### WHOIS 検索"),
    ("### 刷新DNS", "### DNS フラッシュ"),
    ("## 调色板", "## カラーパレット"),
    ("### 主题颜色/标准颜色", "### テーマ / 標準カラー"),
    ("### 屏幕取色器", "### スクリーンカラーピッカー"),
    ("### 自由选色", "### 自由な色選択"),
    ("### 颜色格式转换", "### カラー形式変換"),
    ("### 颜色收藏", "### お気に入りカラー"),
    ("### 颜色混合计算（取反、相交、相加、差值、平均）", "### カラー演算（反転、交差、加算、差分、平均）"),
    ("## 图片助手", "## 画像アシスタント"),
    ("### 本地图床", "### ローカル画像ホスト"),
    ("### 截图", "### スクリーンショット"),
    ("### 从剪贴板获取 / 复制到剪贴板", "### クリップボードから取得 / クリップボードへコピー"),
    ("### 图片缩放工具栏（放大/缩小/原始尺寸/适应窗口）", "### ズームツールバー（拡大/縮小/原寸/ウィンドウに合わせる）"),
    ("### 图片Base64编码/解码", "### 画像 Base64 エンコード / デコード"),
    ("### 图片压缩", "### 画像圧縮"),
    ("### 图片加水印", "### 画像ウォーターマーク"),
    ("### 图片OCR识别（基于 Tesseract）", "### 画像 OCR（Tesseract）"),
    ("## Cron", "## Cron"),
    ("### Cron表达式生成", "### Cron 式ビルダー"),
    ("### Cron表达式解析（支持 Linux 5 段 / Quartz 6、7 段）", "### Cron 式解析（Linux 5 フィールド / Quartz 6〜7 フィールド）"),
    ("### Cron表达式校验", "### Cron 式検証"),
    ("### Cron 转自然语言", "### Cron を自然言語に変換"),
    ("### 最近 10 次运行时间", "### 次の 10 回の実行時刻"),
    ("### Cron表达式收藏", "### お気に入り Cron 式"),
    ("### 常用Cron表达式", "### よく使う Cron 式"),
    ("## 正则", "## 正規表現"),
    ("### 正则表达式匹配测试", "### 正規表現マッチテスト"),
    ("### 收藏正则表达式", "### お気に入り正規表現"),
    ("### 常用正则表达式", "### よく使う正規表現"),
    ("## Java", "## Java"),
    ("### Java/groovy代码格式化、高亮", "### Java/Groovy 整形とハイライト"),
    ("### Java/groovy代码解释执行", "### Java/Groovy インタプリタ実行"),
    ("## 格式化", "## フォーマット"),
    ("### 上传文件格式化", "### アップロードファイルの整形"),
    ("- Nginx 配置文件", "- Nginx 設定"),
    ("### 粘贴文本直接格式化（Nginx / Java / XML / HTML）", "### 貼り付けて整形（Nginx / Java / XML / HTML）"),
    ("## PDF", "## PDF"),
    ("### PDF拆分", "### PDF 分割"),
    ("### PDF合并", "### PDF 結合"),
    ("## 环境变量", "## 環境変数"),
    ("### 系统环境变量（表格浏览）", "### システム環境変数（表形式）"),
    ("### 刷新 / 导出", "### 更新 / エクスポート"),
    ("## 系统信息", "## システム情報"),
    ("基于 OSHI 采集本机系统与硬件信息，首次进入 Tab 或点击刷新时按需加载：",
     "OSHI でローカルのシステム/ハードウェア情報を収集。初回タブ表示または更新時に読み込み："),
    ("### 系统（操作系统、计算机、固件、主板等）", "### システム（OS、コンピュータ、ファームウェア、マザーボードなど）"),
    ("### 处理器", "### CPU"),
    ("### 内存", "### メモリ"),
    ("### 存储", "### ストレージ"),
    ("### 网络", "### ネットワーク"),
    ("## 配置文件转换", "## 設定ファイル変換"),
    ("### Properties->YAML", "### Properties → YAML"),
    ("### YAML->Properties", "### YAML → Properties"),
    ("### YAML 校验（语法校验、错误行号定位）", "### YAML 検証（構文と行番号）"),
    ("### YAML 格式化", "### YAML 整形"),
    ("### JSON->YAML（TODO）", "### JSON → YAML（TODO）"),
    ("### YAML->JSON（TODO）", "### YAML → JSON（TODO）"),
    ("## 文本对比", "## テキスト比較"),
    ("### 并排对比（左右滚动同步）", "### 左右並列比較（スクロール同期）"),
    ("### 统一差异", "### 統合 diff"),
    ("### 复制差异", "### diff をコピー"),
    ("## Protobuf", "## Protobuf"),
    ("### JSON ↔ Protobuf 二进制互转", "### JSON ↔ Protobuf バイナリ変換"),
    ("- 支持 Hex / Base64 输出", "- Hex / Base64 出力"),
    ("- `.proto` 定义格式化", "- `.proto` 定義の整形"),
    ("### Wire Format 解码（无需 `.proto` 定义）", "### Wire Format デコード（`.proto` 不要）"),
    ("### Hex / Base64 互转", "### Hex / Base64 変換"),
    ("## 应用与设置", "## アプリと設定"),
    ("### 同步和备份（Git 同步、数据导出）", "### 同期とバックアップ（Git 同期、データエクスポート）"),
    ("### 快捷键说明", "### キーボードショートカット"),
    ("### 数据文件位置自定义", "### データディレクトリのカスタム"),
    ("### 启动时自动检查更新", "### 起動時に更新を確認"),
    ("### SQL 方言设置", "### SQL 方言"),
    ("### 系统托盘", "### システムトレイ"),
    ("### 窗口行为", "### ウィンドウ動作"),
    ("- macOS / Windows：点击关闭按钮时隐藏到 Dock / 任务栏，应用继续在后台运行",
     "- macOS / Windows：閉じるボタンで Dock / タスクバーに最小化、バックグラウンドで継続"),
    ("- Linux：点击关闭按钮退出应用", "- Linux：閉じるボタンでアプリを終了"),
    ("### 外观", "### 外観"),
    ("- 多主题风格（Flat Light/Dark、macOS、One Dark、Monokai 等）", "- 多数のテーマ（Flat Light/Dark、macOS、One Dark、Monokai など）"),
    ("- 强调色", "- アクセントカラー"),
    ("- 主题颜色跟随系统", "- システムのアクセントに追従"),
    ("- 窗口颜色沉浸式", "- ウィンドウ背景の没入型表示"),
    ("- 默认最大化窗口", "- 起動時に最大化"),
    ("- 功能 Tab 仅图标模式", "- タブをアイコンのみ表示"),
    ("### 使用习惯", "### レイアウト"),
    ("- 功能面板位置（菜单栏上/下/左/右）", "- パネル位置（上/下/左/右）"),
    ("- 全局字体与字号", "- 全体フォントとサイズ"),
    ("## 特别感谢", "## 謝辞"),
    ("## 开发温馨提示", "## 開発者向けメモ"),
    ("多产品的版本号、Git tag、GitHub Release、`Latest` 标记及 CI 隔离规则统一见[多产品发布约定](RELEASE_CONVENTIONS.md)。",
     "複数製品のバージョン、Git tag、GitHub Release、`Latest`、CI 分離ルールについては、[複数製品のリリース規約](RELEASE_CONVENTIONS.md)を参照してください。"),
    ("最低JDK版本要求：**21**", "最低 JDK：**21**"),
    ("在你开始开发之前, **请按下图设置IntelliJ IDEA**, 然后 **maven clean**:",
     "開発を始める前に、**下図のとおり IntelliJ IDEA を設定**し、**maven clean** を実行してください："),
    ("### 打包与 CI", "### パッケージングと CI"),
    ("项目现在支持把打包 JDK 下载并缓存到仓库本地目录：", "パッケージング用 JDK をローカルにダウンロードしてキャッシュできます："),
    ("- JDK 压缩包缓存：`downloads/jdks/`", "- JDK アーカイブ：`downloads/jdks/`"),
    ("- 解压后的 JDK：`jdks/<os>/<arch>/home`", "- 展開済み JDK：`jdks/<os>/<arch>/home`"),
    ("下载脚本默认使用 Eclipse Temurin 21，并且如果本地已经存在对应 JDK，就不会重复下载。",
     "ダウンロードスクリプトは Eclipse Temurin 21 を使用し、既存の JDK がある場合は再ダウンロードしません。"),
    ("#### 先准备本地打包 JDK", "#### ローカルパッケージング JDK の準備"),
    ("也可以一次性查看全部目标会下载到哪里：", "すべてのダウンロード先を一度に確認："),
    ("#### 本地打包命令", "#### ローカルパッケージコマンド"),
    ("默认 `mvn clean package` 仍然会使用当前运行 Maven 的 JDK 打一个 macOS universal 包。",
     "デフォルトの `mvn clean package` は現在の JDK で macOS universal パッケージをビルドします。"),
    ("对于 `mac-intel`、`mac-apple-silicon`、`windows-x64`、`linux-x64` 这几个 profile，Maven 会在 `validate` 阶段先检查 `jdks/` 下是否已经准备好对应 JDK；如果缺失，会直接失败并提示先执行 `scripts/prepare_jdks.py`，避免打出“假成功”的安装包。",
     "プロファイル `mac-intel`、`mac-apple-silicon`、`windows-x64`、`linux-x64` は `validate` 段階で `jdks/` の JDK を検証します。先に `scripts/prepare_jdks.py` を実行しないとビルドは失敗します。"),
    ("如果要使用仓库内缓存 JDK 打指定平台包：", "キャッシュ済み JDK で特定プラットフォーム向けにパッケージ："),
    ("对应产物目录：", "出力ディレクトリ："),
    ("- 默认包：`target/`", "- デフォルト：`target/`"),
    ("- Intel Mac：`target/mac-intel/`", "- Intel Mac：`target/mac-intel/`"),
    ("- Apple Silicon Mac：`target/mac-apple-silicon/`", "- Apple Silicon Mac：`target/mac-apple-silicon/`"),
    ("- Windows x64：`target/windows-x64/`", "- Windows x64：`target/windows-x64/`"),
    ("- Linux x64：`target/linux-x64/`", "- Linux x64：`target/linux-x64/`"),
]
