import Foundation

/// Navigation and workbench strings aligned with Electron `messages.ts` (`app.nav.*`, `app.group.*`).
public enum AppLocalization {
    public static func toolTitle(_ toolID: String, language: AppLanguage) -> String {
        table[language]?[toolID] ?? table[.zhCN]?[toolID] ?? toolID
    }

    public static func toolSubtitle(_ toolID: String, language: AppLanguage, fallback: String) -> String {
        subtitleTable[language]?[toolID] ?? subtitleTable[.zhCN]?[toolID] ?? fallback
    }

    public static func groupTitle(_ group: String, language: AppLanguage) -> String {
        if let key = groupKeys[group], let value = groupTable[language]?[key] { return value }
        return group
    }

    public static func string(_ key: String, language: AppLanguage) -> String {
        ui[language]?[key] ?? ui[.zhCN]?[key] ?? key
    }

    private static let groupKeys: [String: String] = [
        "首页": "home",
        "笔记与文本": "text",
        "开发与格式": "dev",
        "网络与请求": "network",
        "编码与加密": "encode",
        "实用工具": "daily",
        "系统信息": "system"
    ]

    private static let table: [AppLanguage: [String: String]] = [
        .zhCN: [
            "mootool": "主页", "quickNote": "随手记", "textDiff": "文本对比", "reformat": "格式化", "json": "JSON",
            "java": "代码运行", "ymlProperties": "配置转换", "protobuf": "Protobuf", "variables": "环境变量",
            "http": "HTTP", "host": "Host", "net": "网络工具", "uaParse": "UA 解析", "encode": "编码转换",
            "crypto": "加密工具", "regex": "正则表达式", "cron": "Cron", "qrCode": "二维码", "timeConvert": "时间转换",
            "messageBoard": "留言板", "translation": "翻译", "calculator": "计算器", "colorBoard": "调色板",
            "image": "图片工具", "pdf": "PDF", "hardware": "系统信息"
        ],
        .enUS: [
            "mootool": "Home", "quickNote": "Quick Note", "textDiff": "Text Diff", "reformat": "Reformat", "json": "JSON",
            "java": "Code Runner", "ymlProperties": "Config Converter", "protobuf": "Protobuf", "variables": "Environment",
            "http": "HTTP", "host": "Host", "net": "Network/IP", "uaParse": "UA Parser", "encode": "Encode",
            "crypto": "Crypto/Random", "regex": "Regex", "cron": "Cron", "qrCode": "QR Code", "timeConvert": "Time",
            "messageBoard": "Message Board", "translation": "Translation", "calculator": "Calculator", "colorBoard": "Color Board",
            "image": "Images", "pdf": "PDF", "hardware": "System Info"
        ],
        .jaJP: [
            "mootool": "ホーム", "quickNote": "クイックノート", "textDiff": "テキスト比較", "reformat": "整形", "json": "JSON",
            "java": "コード実行", "ymlProperties": "設定変換", "protobuf": "Protobuf", "variables": "環境変数",
            "http": "HTTP", "host": "Host", "net": "ネットワーク", "uaParse": "UA 解析", "encode": "エンコード",
            "crypto": "暗号化", "regex": "正規表現", "cron": "Cron", "qrCode": "QR コード", "timeConvert": "時間変換",
            "messageBoard": "メッセージボード", "translation": "翻訳", "calculator": "電卓", "colorBoard": "カラーボード",
            "image": "画像", "pdf": "PDF", "hardware": "システム情報"
        ]
    ]

    private static let subtitleTable: [AppLanguage: [String: String]] = [
        .zhCN: [
            "mootool": "触手可及的开发与日常工具", "quickNote": "记录想法，整理 Markdown 笔记", "textDiff": "逐行与字符高亮、统一差异和变更导航",
            "reformat": "整理 Nginx、Java、XML、HTML 和 JSON 文本与文件", "json": "格式化、压缩、校验与路径查询", "java": "运行本机的 JavaScript、Python、Swift 与 Java",
            "ymlProperties": "YAML、JSON 与 Properties 互转", "protobuf": "查看 Protobuf wire 字段及二进制数据", "variables": "查看进程环境，编辑独立的运行变量",
            "http": "发送请求，检查响应头、耗时和正文", "host": "读取系统 Hosts，编辑和导出配置", "net": "DNS、Ping、Whois 与网络接口",
            "uaParse": "识别 User-Agent 中的浏览器、系统与设备", "encode": "Base64、Base32、URL、Hex、Unicode 与 HTML 实体",
            "crypto": "摘要、HMAC、AES-GCM、UUID 与随机数据", "regex": "匹配、捕获分组与替换", "cron": "解析五段 Cron，预览接下来的执行时间",
            "qrCode": "生成、保存与识别二维码", "timeConvert": "时间戳、日期和时区转换", "messageBoard": "用全屏大字展示你的留言",
            "translation": "使用 macOS 系统翻译或查询词典", "calculator": "数学表达式、函数与进制转换", "colorBoard": "颜色选择、屏幕取色与 HEX / RGB / HSL",
            "image": "预览、缩放、转换格式与压缩图片", "pdf": "预览、合并、提取页面与导出文本", "hardware": "查看系统版本、处理器、内存与磁盘"
        ],
        .enUS: [
            "mootool": "Desktop tools for developers", "quickNote": "Capture ideas and Markdown notes", "textDiff": "Line/char diff, unified patch, navigation",
            "reformat": "Format Nginx, Java, XML, HTML, and JSON", "json": "Format, minify, validate, and query paths", "java": "Run local JavaScript, Python, Swift, and Java",
            "ymlProperties": "Convert YAML, JSON, and Properties", "protobuf": "Inspect Protobuf wire fields and binary", "variables": "View process env and run variables",
            "http": "Send requests and inspect responses", "host": "Read system hosts and edit profiles", "net": "DNS, ping, whois, and interfaces",
            "uaParse": "Parse browser, OS, and device from UA", "encode": "Base64, Base32, URL, hex, Unicode, HTML entities",
            "crypto": "Digests, HMAC, AES-GCM, UUID, random data", "regex": "Match, capture groups, replace", "cron": "Parse cron and preview next runs",
            "qrCode": "Generate, save, and scan QR codes", "timeConvert": "Timestamps, dates, and time zones", "messageBoard": "Fullscreen message display",
            "translation": "macOS Translation and word book", "calculator": "Expressions, functions, radix convert", "colorBoard": "Pick colors and screen sampling",
            "image": "Preview, resize, convert, compress", "pdf": "Preview, merge, extract pages, text export", "hardware": "OS, CPU, memory, and disk info"
        ],
        .jaJP: [
            "mootool": "開発者向けデスクトップツール", "quickNote": "アイデアと Markdown メモ", "textDiff": "行/文字差分と統一パッチ",
            "reformat": "Nginx、Java、XML、HTML、JSON の整形", "json": "整形・圧縮・検証・パス照会", "java": "ローカルで JS/Python/Swift/Java を実行",
            "ymlProperties": "YAML・JSON・Properties 変換", "protobuf": "Protobuf wire とバイナリ", "variables": "プロセス環境と実行用変数",
            "http": "HTTP リクエストとレスポンス", "host": "Hosts の読み取りと編集", "net": "DNS、ping、whois、IF",
            "uaParse": "UA からブラウザ/OS/端末を推定", "encode": "Base64、URL、Hex など", "crypto": "ハッシュ、HMAC、AES、乱数",
            "regex": "正規表現のマッチと置換", "cron": "Cron 解析と次回実行", "qrCode": "QR コードの生成と読取",
            "timeConvert": "タイムスタンプとタイムゾーン", "messageBoard": "全画面メッセージ表示", "translation": "macOS 翻訳と単語帳",
            "calculator": "式・関数・基数変換", "colorBoard": "カラー選択と画面取色", "image": "画像のプレビューと変換",
            "pdf": "PDF プレビュー・結合・抽出", "hardware": "OS・CPU・メモリ・ディスク"
        ]
    ]

    private static let groupTable: [AppLanguage: [String: String]] = [
        .zhCN: ["home": "首页", "text": "笔记与文本", "dev": "开发与格式", "network": "网络与请求", "encode": "编码与加密", "daily": "实用工具", "system": "系统信息"],
        .enUS: ["home": "Home", "text": "Notes & Text", "dev": "Development & Format", "network": "Network & Requests", "encode": "Encoding & Crypto", "daily": "Utilities", "system": "System"],
        .jaJP: ["home": "ホーム", "text": "ノートとテキスト", "dev": "開発と整形", "network": "ネットワーク", "encode": "エンコードと暗号", "daily": "ユーティリティ", "system": "システム"]
    ]

    private static let ui: [AppLanguage: [String: String]] = [
        .zhCN: [
            "settings.language": "界面语言",
            "settings.autoCheckUpdates": "启动时检查更新",
            "app.nav.recent": "最近使用",
            "app.nav.search": "搜索",
            "app.nav.settings": "设置",
            "app.group.all": "全部工具",
            "app.search.title": "搜索工具",
            "app.search.placeholder": "搜索功能…",
            "update.available.title": "发现新版本",
            "update.upToDate": "当前已是最新版本。",
            "update.failed": "无法检查更新，请稍后重试或手动打开 GitHub Releases。",
            "update.openDownload": "打开下载页面",
            "update.later": "稍后",
            "tool.ready": "就绪",
            "editor.chars": "字符",
            "editor.paste": "粘贴",
            "editor.openFile": "打开文本文件",
            "editor.copy": "复制",
            "editor.export": "导出文本",
            "settings.category.sidebar": "侧边栏",
            "settings.category.proxy": "HTTP 代理",
            "settings.category.appearance": "外观",
            "settings.category.vault": "文档库 Git",
            "settings.category.migration": "数据迁移",
            "settings.category.backup": "工作区与备份",
            "settings.category.shortcuts": "快捷键",
            "settings.category.about": "关于",
            "settings.customGroups": "自定义分组",
            "settings.manageCustomGroups": "管理自定义分组…",
            "settings.hiddenNavTools": "侧栏隐藏工具",
            "settings.manageHiddenNav": "管理侧栏工具显示…",
            "settings.notConfigured": "未配置",
            "settings.none": "无",
            "settings.countUnit": "个",
            "settings.showGroupSeparators": "显示分组分隔线",
            "settings.showRecent": "显示最近使用",
            "settings.sidebarWidth": "侧栏宽度",
            "settings.trayEnabled": "启用菜单栏图标（托盘）",
            "settings.closeWindow": "关闭主窗口",
            "settings.close.ask": "每次询问",
            "settings.close.hide": "隐藏窗口",
            "settings.close.quit": "退出应用",
            "settings.autoDownloadPref": "有更新时自动下载（偏好）",
            "settings.proxyEnabled": "使用 HTTP 代理",
            "settings.host": "主机",
            "settings.port": "端口",
            "settings.usernameOptional": "用户名（可选）",
            "settings.passwordOptional": "密码（可选）",
            "tool.bigClock": "大时钟",
            "settings.theme": "主题",
            "settings.theme.system": "跟随系统",
            "settings.theme.light": "浅色",
            "settings.theme.dark": "深色",
            "settings.editorFontSize": "编辑器字号",
            "settings.wrapLines": "编辑器自动换行",
            "settings.vaultAutoCommit": "编辑空闲后自动创建检查点",
            "settings.importElectron": "从 Electron 导入工作台设置…",
            "settings.version": "版本",
            "settings.tech": "技术",
            "settings.viewProject": "查看项目与反馈问题 ↗",
            "settings.productLine": "产品线",
            "settings.showInFinder": "在 Finder 中显示",
            "settings.exportBackup": "导出备份",
            "settings.importBackup": "导入备份…",
            "host.readSystem": "读取系统 Hosts",
            "host.validate": "检查配置",
            "host.export": "导出 hosts",
            "common.done": "完成",
            "history.restore": "恢复",
            "history.empty.title": "暂无历史记录",
            "history.empty.description": "运行工具后，结果会保存在这里。",
            "tray.open": "打开 MooTool",
            "tray.settings": "设置…",
            "tray.pickColor": "屏幕取色",
            "tray.screenshot": "区域截图",
            "tray.translate": "翻译",
            "tray.quit": "退出 MooTool",
            "color.choose": "选择颜色",
            "color.screenPick": "屏幕取色",
            "color.applyHex": "应用 HEX",
            "color.values": "颜色值",
            "palette.cancel": "取消",
            "palette.hint": "↑ ↓ 选择 · ↩ 打开 · Esc 关闭",
            "palette.count": "个工具",
            "settings.shortcut.search": "搜索工具",
            "settings.shortcut.settings": "打开设置",
            "tool.input": "输入",
            "tool.output": "结果",
            "tool.run": "运行",
            "tool.example": "示例",
            "tool.clear": "清空输入和结果",
            "tool.format": "格式化",
            "tool.minify": "压缩",
            "tool.encode": "编码",
            "tool.decode": "解码",
            "tool.convert": "转换",
            "tool.now": "此刻",
            "tool.query": "查询",
            "tool.send": "发送",
            "workbench.search": "搜索工具",
            "workbench.pinned": "常用",
            "workbench.history": "历史记录",
            "workbench.detach": "独立窗口",
            "workbench.alert.title": "工作区提示",
            "workbench.alert.ok": "好",
            "workbench.pinHelp": "添加或移出常用工具",
            "workbench.sidebar.expand": "展开导航标题",
            "workbench.sidebar.iconsOnly": "仅显示图标",
            "workbench.settingsHelp": "设置 · ⌘,",
            "tool.runCode": "运行代码",
            "tool.stop": "停止",
            "tool.parse": "解析",
            "tool.translate": "翻译",
            "tool.fullscreen": "全屏展示",
            "tool.generateQr": "生成二维码",
            "tool.openImage": "打开图片",
            "tool.addPdf": "添加 PDF",
            "tool.newProfile": "新建配置",
            "tool.saveProfile": "保存配置",
            "tool.genKeyPair": "生成密钥对",
            "tool.digestText": "文本摘要",
            "tool.refreshSystemInfo": "刷新系统信息",
            "tool.refreshEnv": "查看当前环境",
            "tool.cronPreview": "预览执行时间",
            "tool.favorites": "收藏",
            "http.request": "请求",
            "http.response": "响应",
            "http.tab.params": "参数",
            "http.tab.headers": "请求头",
            "http.tab.cookies": "Cookie",
            "http.tab.body": "正文",
            "http.importCurl": "导入 cURL…",
            "http.copyCurl": "复制为 cURL",
            "http.saveToCollection": "保存到请求集合…",
            "http.openCollection": "打开请求集合…",
            "http.newRequest": "新建请求",
            "http.menuHelp": "cURL 与请求集合",
            "http.collection": "请求集合",
            "http.saveRequest": "保存当前请求",
            "http.cancelRequest": "取消请求",
            "http.followRedirects": "跟随重定向",
            "http.timeout": "超时",
            "http.seconds": "秒",
            "http.importCurlShort": "导入 cURL",
            "http.prettyJson": "JSON 格式化显示",
            "app.menu.about": "关于 MooTool Next Native",
            "app.menu.searchTools": "搜索工具…",
            "app.menu.checkUpdate": "检查更新…",
            "app.menu.tools": "工具",
            "translation.tab.translate": "翻译",
            "translation.tab.words": "词库",
            "translation.tab.history": "历史",
            "translation.applyToTranslate": "填入翻译页",
            "translation.source": "原文",
            "translation.target": "译文",
            "tool.new": "新建",
            "tool.save": "保存",
            "tool.delete": "删除",
            "translation.sourceAuto": "原文 · 自动识别语言",
            "translation.systemDictionary": "系统词典",
            "home.tagline": "开发与日常，得心应手。",
            "home.byAuthor": "由 Zhou Bo 创作",
            "home.section.about": "关于",
            "home.section.contributors": "贡献者",
            "home.section.sponsor": "赞赏",
            "home.section.source": "源码与反馈",
            "home.section.otherWorks": "其他作品",
            "home.aboutBody": "MooTool 是面向开发者与日常效率的桌面工具箱。原生版保留 26 个工具入口与工作区，数据独立保存在本机。",
            "home.contributorsThanks": "感谢每一位为 MooTool 生态贡献想法、代码与反馈的朋友。",
            "home.sponsorText": "如果 MooTool 对你有帮助，欢迎请作者喝杯咖啡。",
            "home.sponsorCaption": "微信赞赏码",
            "home.searchTools": "查找你需要的工具",
            "home.forMac.title": "为 Mac 而生",
            "home.forMac.body": "熟悉的 MooTool 工作方式，原生的 macOS 体验。通过侧边栏探索文本、开发、网络、编码和日常工具，也可以把工具单独打开，让工作区更从容。",
            "home.localSave": "本地保存",
            "home.standaloneInstall": "独立安装",
            "home.nativeShortcuts": "原生快捷键"
        ],
        .enUS: [
            "settings.language": "Language",
            "settings.autoCheckUpdates": "Check for updates on launch",
            "app.nav.recent": "Recent",
            "app.nav.search": "Search",
            "app.nav.settings": "Settings",
            "app.group.all": "All tools",
            "app.search.title": "Search tools",
            "app.search.placeholder": "Search tools…",
            "update.available.title": "Update available",
            "update.upToDate": "You are on the latest version.",
            "update.failed": "Could not check for updates. Try again later or open GitHub Releases.",
            "update.openDownload": "Open download page",
            "update.later": "Later",
            "tool.ready": "Ready",
            "editor.chars": "chars",
            "editor.paste": "Paste",
            "editor.openFile": "Open text file",
            "editor.copy": "Copy",
            "editor.export": "Export text",
            "settings.category.sidebar": "Sidebar",
            "settings.category.proxy": "HTTP Proxy",
            "settings.category.appearance": "Appearance",
            "settings.category.vault": "Vault Git",
            "settings.category.migration": "Data Migration",
            "settings.category.backup": "Workspace & Backup",
            "settings.category.shortcuts": "Shortcuts",
            "settings.category.about": "About",
            "settings.customGroups": "Custom groups",
            "settings.manageCustomGroups": "Manage custom groups…",
            "settings.hiddenNavTools": "Hidden sidebar tools",
            "settings.manageHiddenNav": "Manage sidebar visibility…",
            "settings.notConfigured": "Not configured",
            "settings.none": "None",
            "settings.countUnit": "",
            "settings.showGroupSeparators": "Show group separators",
            "settings.showRecent": "Show recent tools",
            "settings.sidebarWidth": "Sidebar width",
            "settings.trayEnabled": "Menu bar icon (tray)",
            "settings.closeWindow": "Close main window",
            "settings.close.ask": "Ask every time",
            "settings.close.hide": "Hide window",
            "settings.close.quit": "Quit app",
            "settings.autoDownloadPref": "Auto-download updates (preference)",
            "settings.proxyEnabled": "Use HTTP proxy",
            "settings.host": "Host",
            "settings.port": "Port",
            "settings.usernameOptional": "Username (optional)",
            "settings.passwordOptional": "Password (optional)",
            "tool.bigClock": "Large clock",
            "settings.theme": "Theme",
            "settings.theme.system": "System",
            "settings.theme.light": "Light",
            "settings.theme.dark": "Dark",
            "settings.editorFontSize": "Editor font size",
            "settings.wrapLines": "Wrap editor lines",
            "settings.vaultAutoCommit": "Auto-checkpoint after idle editing",
            "settings.importElectron": "Import from Electron…",
            "settings.version": "Version",
            "settings.tech": "Technology",
            "settings.viewProject": "View project and issues ↗",
            "settings.productLine": "Product",
            "settings.showInFinder": "Reveal in Finder",
            "settings.exportBackup": "Export backup",
            "settings.importBackup": "Import backup…",
            "host.readSystem": "Read system hosts",
            "host.validate": "Validate profile",
            "host.export": "Export hosts",
            "common.done": "Done",
            "history.restore": "Restore",
            "history.empty.title": "No history yet",
            "history.empty.description": "Results appear here after you run the tool.",
            "tray.open": "Open MooTool",
            "tray.settings": "Settings…",
            "tray.pickColor": "Screen color picker",
            "tray.screenshot": "Region screenshot",
            "tray.translate": "Translation",
            "tray.quit": "Quit MooTool",
            "color.choose": "Pick color",
            "color.screenPick": "Sample screen",
            "color.applyHex": "Apply HEX",
            "color.values": "Color values",
            "palette.cancel": "Cancel",
            "palette.hint": "↑ ↓ select · ↩ open · Esc close",
            "palette.count": "tools",
            "settings.shortcut.search": "Search tools",
            "settings.shortcut.settings": "Open settings",
            "tool.input": "Input",
            "tool.output": "Output",
            "tool.run": "Run",
            "tool.example": "Example",
            "tool.clear": "Clear input and output",
            "tool.format": "Format",
            "tool.minify": "Minify",
            "tool.encode": "Encode",
            "tool.decode": "Decode",
            "tool.convert": "Convert",
            "tool.now": "Now",
            "tool.query": "Query",
            "tool.send": "Send",
            "workbench.search": "Search tools",
            "workbench.pinned": "Pinned",
            "workbench.history": "History",
            "workbench.detach": "Detach window",
            "workbench.alert.title": "Workspace notice",
            "workbench.alert.ok": "OK",
            "workbench.pinHelp": "Pin or unpin this tool",
            "workbench.sidebar.expand": "Show navigation titles",
            "workbench.sidebar.iconsOnly": "Icons only",
            "workbench.settingsHelp": "Settings · ⌘,",
            "tool.runCode": "Run code",
            "tool.stop": "Stop",
            "tool.parse": "Parse",
            "tool.translate": "Translate",
            "tool.fullscreen": "Fullscreen",
            "tool.generateQr": "Generate QR",
            "tool.openImage": "Open image",
            "tool.addPdf": "Add PDF",
            "tool.newProfile": "New profile",
            "tool.saveProfile": "Save profile",
            "tool.genKeyPair": "Generate key pair",
            "tool.digestText": "Digest text",
            "tool.refreshSystemInfo": "Refresh system info",
            "tool.refreshEnv": "View environment",
            "tool.cronPreview": "Preview schedule",
            "tool.favorites": "Favorites",
            "http.request": "Request",
            "http.response": "Response",
            "http.tab.params": "Params",
            "http.tab.headers": "Headers",
            "http.tab.cookies": "Cookies",
            "http.tab.body": "Body",
            "http.importCurl": "Import cURL…",
            "http.copyCurl": "Copy as cURL",
            "http.saveToCollection": "Save to collection…",
            "http.openCollection": "Open collection…",
            "http.newRequest": "New request",
            "http.menuHelp": "cURL and collections",
            "http.collection": "Collection",
            "http.saveRequest": "Save request",
            "http.cancelRequest": "Cancel",
            "http.followRedirects": "Follow redirects",
            "http.timeout": "Timeout",
            "http.seconds": "s",
            "http.importCurlShort": "Import cURL",
            "http.prettyJson": "Pretty-print JSON",
            "app.menu.about": "About MooTool Next Native",
            "app.menu.searchTools": "Search Tools…",
            "app.menu.checkUpdate": "Check for Updates…",
            "app.menu.tools": "Tools",
            "translation.tab.translate": "Translate",
            "translation.tab.words": "Word book",
            "translation.tab.history": "History",
            "translation.applyToTranslate": "Use in translate tab",
            "translation.source": "Source",
            "translation.target": "Translation",
            "tool.new": "New",
            "tool.save": "Save",
            "tool.delete": "Delete",
            "translation.sourceAuto": "Source · auto-detect",
            "translation.systemDictionary": "System dictionary",
            "home.tagline": "Development and daily tasks, at hand.",
            "home.byAuthor": "By Zhou Bo",
            "home.section.about": "About",
            "home.section.contributors": "Contributors",
            "home.section.sponsor": "Sponsor",
            "home.section.source": "Source & feedback",
            "home.section.otherWorks": "More projects",
            "home.aboutBody": "MooTool is a desktop toolbox for developers and everyday productivity. Native keeps 26 tool entries and an independent on-device workspace.",
            "home.contributorsThanks": "Thanks to everyone who contributes ideas, code, and feedback to MooTool.",
            "home.sponsorText": "If MooTool helps you, consider buying the author a coffee.",
            "home.sponsorCaption": "WeChat tip QR",
            "home.searchTools": "Find a tool",
            "home.forMac.title": "Built for Mac",
            "home.forMac.body": "The familiar MooTool workflow with a native macOS experience. Explore text, dev, network, encoding, and daily tools in the sidebar—or open tools in their own windows.",
            "home.localSave": "On-device data",
            "home.standaloneInstall": "Standalone install",
            "home.nativeShortcuts": "Native shortcuts"
        ],
        .jaJP: [
            "settings.language": "表示言語",
            "settings.autoCheckUpdates": "起動時に更新を確認",
            "app.nav.recent": "最近",
            "app.nav.search": "検索",
            "app.nav.settings": "設定",
            "app.group.all": "すべてのツール",
            "app.search.title": "ツールを検索",
            "app.search.placeholder": "ツールを検索…",
            "update.available.title": "新しいバージョンがあります",
            "update.upToDate": "最新バージョンです。",
            "update.failed": "更新を確認できませんでした。後でもう一度試すか GitHub Releases を開いてください。",
            "update.openDownload": "ダウンロードページを開く",
            "update.later": "後で",
            "tool.ready": "準備完了",
            "editor.chars": "文字",
            "editor.paste": "貼り付け",
            "editor.openFile": "テキストを開く",
            "editor.copy": "コピー",
            "editor.export": "テキストを書き出す",
            "settings.category.sidebar": "サイドバー",
            "settings.category.proxy": "HTTP プロキシ",
            "settings.category.appearance": "外観",
            "settings.category.vault": "ドキュメント Git",
            "settings.category.migration": "データ移行",
            "settings.category.backup": "ワークスペースとバックアップ",
            "settings.category.shortcuts": "ショートカット",
            "settings.category.about": "情報",
            "settings.customGroups": "カスタムグループ",
            "settings.manageCustomGroups": "カスタムグループを管理…",
            "settings.hiddenNavTools": "非表示のサイドバーツール",
            "settings.manageHiddenNav": "サイドバーの表示を管理…",
            "settings.notConfigured": "未設定",
            "settings.none": "なし",
            "settings.countUnit": "件",
            "settings.showGroupSeparators": "グループ区切りを表示",
            "settings.showRecent": "最近使ったツールを表示",
            "settings.sidebarWidth": "サイドバー幅",
            "settings.trayEnabled": "メニューバーアイコン（トレイ）",
            "settings.closeWindow": "メインウィンドウを閉じる",
            "settings.close.ask": "毎回確認",
            "settings.close.hide": "ウィンドウを隠す",
            "settings.close.quit": "アプリを終了",
            "settings.autoDownloadPref": "更新を自動ダウンロード（設定）",
            "settings.proxyEnabled": "HTTP プロキシを使用",
            "settings.host": "ホスト",
            "settings.port": "ポート",
            "settings.usernameOptional": "ユーザー名（任意）",
            "settings.passwordOptional": "パスワード（任意）",
            "tool.bigClock": "大きな時計",
            "settings.theme": "テーマ",
            "settings.theme.system": "システムに合わせる",
            "settings.theme.light": "ライト",
            "settings.theme.dark": "ダーク",
            "settings.editorFontSize": "エディタの文字サイズ",
            "settings.wrapLines": "エディタで折り返し",
            "settings.vaultAutoCommit": "編集アイドル後に自動チェックポイント",
            "settings.importElectron": "Electron からインポート…",
            "settings.version": "バージョン",
            "settings.tech": "技術",
            "settings.viewProject": "プロジェクトと Issue ↗",
            "settings.productLine": "プロダクト",
            "settings.showInFinder": "Finder で表示",
            "settings.exportBackup": "バックアップを書き出す",
            "settings.importBackup": "バックアップを読み込む…",
            "host.readSystem": "システム Hosts を読み込む",
            "host.validate": "プロファイルを検証",
            "host.export": "hosts を書き出す",
            "common.done": "完了",
            "history.restore": "復元",
            "history.empty.title": "履歴がありません",
            "history.empty.description": "ツールを実行すると、ここに結果が保存されます。",
            "tray.open": "MooTool を開く",
            "tray.settings": "設定…",
            "tray.pickColor": "画面から色を取得",
            "tray.screenshot": "範囲スクリーンショット",
            "tray.translate": "翻訳",
            "tray.quit": "MooTool を終了",
            "color.choose": "色を選択",
            "color.screenPick": "画面から取色",
            "color.applyHex": "HEX を適用",
            "color.values": "色の値",
            "palette.cancel": "キャンセル",
            "palette.hint": "↑ ↓ 選択 · ↩ 開く · Esc 閉じる",
            "palette.count": "件のツール",
            "settings.shortcut.search": "ツールを検索",
            "settings.shortcut.settings": "設定を開く",
            "tool.input": "入力",
            "tool.output": "結果",
            "tool.run": "実行",
            "tool.example": "例",
            "tool.clear": "入力と結果をクリア",
            "tool.format": "整形",
            "tool.minify": "圧縮",
            "tool.encode": "エンコード",
            "tool.decode": "デコード",
            "tool.convert": "変換",
            "tool.now": "現在",
            "tool.query": "照会",
            "tool.send": "送信",
            "workbench.search": "ツールを検索",
            "workbench.pinned": "ピン留め",
            "workbench.history": "履歴",
            "workbench.detach": "別ウィンドウ",
            "workbench.alert.title": "ワークスペース",
            "workbench.alert.ok": "OK",
            "workbench.pinHelp": "ピン留めの追加/解除",
            "workbench.sidebar.expand": "ナビのタイトルを表示",
            "workbench.sidebar.iconsOnly": "アイコンのみ",
            "workbench.settingsHelp": "設定 · ⌘,",
            "tool.runCode": "コードを実行",
            "tool.stop": "停止",
            "tool.parse": "解析",
            "tool.translate": "翻訳",
            "tool.fullscreen": "全画面表示",
            "tool.generateQr": "QR を生成",
            "tool.openImage": "画像を開く",
            "tool.addPdf": "PDF を追加",
            "tool.newProfile": "新規プロファイル",
            "tool.saveProfile": "プロファイルを保存",
            "tool.genKeyPair": "鍵ペアを生成",
            "tool.digestText": "テキストを要約",
            "tool.refreshSystemInfo": "システム情報を更新",
            "tool.refreshEnv": "環境を表示",
            "tool.cronPreview": "実行予定をプレビュー",
            "tool.favorites": "お気に入り",
            "http.request": "リクエスト",
            "http.response": "レスポンス",
            "http.tab.params": "パラメータ",
            "http.tab.headers": "ヘッダー",
            "http.tab.cookies": "Cookie",
            "http.tab.body": "本文",
            "http.importCurl": "cURL をインポート…",
            "http.copyCurl": "cURL としてコピー",
            "http.saveToCollection": "コレクションに保存…",
            "http.openCollection": "コレクションを開く…",
            "http.newRequest": "新規リクエスト",
            "http.menuHelp": "cURL とコレクション",
            "http.collection": "コレクション",
            "http.saveRequest": "リクエストを保存",
            "http.cancelRequest": "キャンセル",
            "http.followRedirects": "リダイレクトを追従",
            "http.timeout": "タイムアウト",
            "http.seconds": "秒",
            "http.importCurlShort": "cURL をインポート",
            "http.prettyJson": "JSON を整形表示",
            "app.menu.about": "MooTool Next Native について",
            "app.menu.searchTools": "ツールを検索…",
            "app.menu.checkUpdate": "更新を確認…",
            "app.menu.tools": "ツール",
            "translation.tab.translate": "翻訳",
            "translation.tab.words": "単語帳",
            "translation.tab.history": "履歴",
            "translation.applyToTranslate": "翻訳タブに入力",
            "translation.source": "原文",
            "translation.target": "訳文",
            "tool.new": "新規",
            "tool.save": "保存",
            "tool.delete": "削除",
            "translation.sourceAuto": "原文 · 言語自動",
            "translation.systemDictionary": "システム辞書",
            "home.tagline": "開発も日常も、手のひらに。",
            "home.byAuthor": "Zhou Bo 作",
            "home.section.about": "概要",
            "home.section.contributors": "コントリビューター",
            "home.section.sponsor": "支援",
            "home.section.source": "ソースとフィードバック",
            "home.section.otherWorks": "その他の作品",
            "home.aboutBody": "MooTool は開発者と日常の効率向けのデスクトップツールボックスです。ネイティブ版は 26 ツールと独立したローカルワークスペースを提供します。",
            "home.contributorsThanks": "MooTool エコシステムに貢献してくださる皆さんに感謝します。",
            "home.sponsorText": "MooTool が役に立ったら、作者にコーヒーを一杯どうぞ。",
            "home.sponsorCaption": "WeChat チップ QR",
            "home.searchTools": "ツールを探す",
            "home.forMac.title": "Mac のために",
            "home.forMac.body": "おなじみの MooTool の使い方を、ネイティブ macOS 体験で。サイドバーでテキスト・開発・ネットワーク・エンコード・日常ツールを探索し、ツールを別ウィンドウで開くこともできます。",
            "home.localSave": "ローカル保存",
            "home.standaloneInstall": "独立インストール",
            "home.nativeShortcuts": "ネイティブショートカット"
        ]
    ]
}

public extension Tool {
    func localized(in language: AppLanguage) -> Tool {
        Tool(
            id,
            AppLocalization.toolTitle(id, language: language),
            symbol,
            AppLocalization.groupTitle(group, language: language),
            AppLocalization.toolSubtitle(id, language: language, fallback: subtitle),
            keywords)
    }
}

public extension Catalog {
    static func localizedTools(_ language: AppLanguage) -> [Tool] {
        tools.map { $0.localized(in: language) }
    }

    static func localizedTool(_ id: String, language: AppLanguage) -> Tool {
        tool(id).localized(in: language)
    }
}
