import Foundation

/// Navigation and workbench strings aligned with Electron `messages.ts` (`app.nav.*`, `app.group.*`).
public enum AppLocalization {
    public static func toolTitle(_ toolID: String, language: AppLanguage) -> String {
        table[language]?[toolID] ?? table[.zhCN]?[toolID] ?? toolID
    }

    public static func toolSubtitle(_ toolID: String, language: AppLanguage, fallback: String) -> String {
        subtitleTable[language]?[toolID] ?? subtitleTable[.zhCN]?[toolID] ?? fallback
    }

    public static func groupTitle(_ group: String, language: AppLanguage) -> String {
        if let key = groupKeys[group], let value = groupTable[language]?[key] { return value }
        return group
    }

    public static func string(_ key: String, language: AppLanguage) -> String {
        ui[language]?[key] ?? ui[.zhCN]?[key] ?? key
    }

    private static let groupKeys: [String: String] = [
        "首页": "home",
        "笔记与文本": "text",
        "开发与格式": "dev",
        "网络与请求": "network",
        "编码与加密": "encode",
        "实用工具": "daily",
        "系统信息": "system"
    ]

    private static let table: [AppLanguage: [String: String]] = [
        .zhCN: [
            "mootool": "主页", "quickNote": "随手记", "textDiff": "文本对比", "reformat": "格式化", "json": "JSON",
            "java": "代码运行", "ymlProperties": "配置转换", "protobuf": "Protobuf", "variables": "环境变量",
            "http": "HTTP", "host": "Host", "net": "网络工具", "uaParse": "UA 解析", "encode": "编码转换",
            "crypto": "加密工具", "regex": "正则表达式", "cron": "Cron", "qrCode": "二维码", "timeConvert": "时间转换",
            "messageBoard": "留言板", "translation": "翻译", "calculator": "计算器", "colorBoard": "调色板",
            "image": "图片工具", "pdf": "PDF", "hardware": "系统信息"
        ],
        .enUS: [
            "mootool": "Home", "quickNote": "Quick Note", "textDiff": "Text Diff", "reformat": "Reformat", "json": "JSON",
            "java": "Code Runner", "ymlProperties": "Config Converter", "protobuf": "Protobuf", "variables": "Environment",
            "http": "HTTP", "host": "Host", "net": "Network/IP", "uaParse": "UA Parser", "encode": "Encode",
            "crypto": "Crypto/Random", "regex": "Regex", "cron": "Cron", "qrCode": "QR Code", "timeConvert": "Time",
            "messageBoard": "Message Board", "translation": "Translation", "calculator": "Calculator", "colorBoard": "Color Board",
            "image": "Images", "pdf": "PDF", "hardware": "System Info"
        ],
        .jaJP: [
            "mootool": "ホーム", "quickNote": "クイックノート", "textDiff": "テキスト比較", "reformat": "整形", "json": "JSON",
            "java": "コード実行", "ymlProperties": "設定変換", "protobuf": "Protobuf", "variables": "環境変数",
            "http": "HTTP", "host": "Host", "net": "ネットワーク", "uaParse": "UA 解析", "encode": "エンコード",
            "crypto": "暗号化", "regex": "正規表現", "cron": "Cron", "qrCode": "QR コード", "timeConvert": "時間変換",
            "messageBoard": "メッセージボード", "translation": "翻訳", "calculator": "電卓", "colorBoard": "カラーボード",
            "image": "画像", "pdf": "PDF", "hardware": "システム情報"
        ]
    ]

    private static let subtitleTable: [AppLanguage: [String: String]] = [
        .zhCN: [
            "mootool": "触手可及的开发与日常工具", "quickNote": "记录想法，整理 Markdown 笔记", "textDiff": "逐行与字符高亮、统一差异和变更导航",
            "reformat": "整理 Nginx、Java、XML、HTML 和 JSON 文本与文件", "json": "格式化、压缩、校验与路径查询", "java": "运行本机的 JavaScript、Python、Swift 与 Java",
            "ymlProperties": "YAML、JSON 与 Properties 互转", "protobuf": "查看 Protobuf wire 字段及二进制数据", "variables": "查看进程环境，编辑独立的运行变量",
            "http": "发送请求，检查响应头、耗时和正文", "host": "读取系统 Hosts，编辑和导出配置", "net": "DNS、Ping、Whois 与网络接口",
            "uaParse": "识别 User-Agent 中的浏览器、系统与设备", "encode": "Base64、Base32、URL、Hex、Unicode 与 HTML 实体",
            "crypto": "摘要、HMAC、AES-GCM、UUID 与随机数据", "regex": "匹配、捕获分组与替换", "cron": "解析五段 Cron，预览接下来的执行时间",
            "qrCode": "生成、保存与识别二维码", "timeConvert": "时间戳、日期和时区转换", "messageBoard": "用全屏大字展示你的留言",
            "translation": "使用 macOS 系统翻译或查询词典", "calculator": "数学表达式、函数与进制转换", "colorBoard": "颜色选择、屏幕取色与 HEX / RGB / HSL",
            "image": "预览、缩放、转换格式与压缩图片", "pdf": "预览、合并、提取页面与导出文本", "hardware": "查看系统版本、处理器、内存与磁盘"
        ],
        .enUS: [
            "mootool": "Desktop tools for developers", "quickNote": "Capture ideas and Markdown notes", "textDiff": "Line/char diff, unified patch, navigation",
            "reformat": "Format Nginx, Java, XML, HTML, and JSON", "json": "Format, minify, validate, and query paths", "java": "Run local JavaScript, Python, Swift, and Java",
            "ymlProperties": "Convert YAML, JSON, and Properties", "protobuf": "Inspect Protobuf wire fields and binary", "variables": "View process env and run variables",
            "http": "Send requests and inspect responses", "host": "Read system hosts and edit profiles", "net": "DNS, ping, whois, and interfaces",
            "uaParse": "Parse browser, OS, and device from UA", "encode": "Base64, Base32, URL, hex, Unicode, HTML entities",
            "crypto": "Digests, HMAC, AES-GCM, UUID, random data", "regex": "Match, capture groups, replace", "cron": "Parse cron and preview next runs",
            "qrCode": "Generate, save, and scan QR codes", "timeConvert": "Timestamps, dates, and time zones", "messageBoard": "Fullscreen message display",
            "translation": "macOS Translation and word book", "calculator": "Expressions, functions, radix convert", "colorBoard": "Pick colors and screen sampling",
            "image": "Preview, resize, convert, compress", "pdf": "Preview, merge, extract pages, text export", "hardware": "OS, CPU, memory, and disk info"
        ],
        .jaJP: [
            "mootool": "開発者向けデスクトップツール", "quickNote": "アイデアと Markdown メモ", "textDiff": "行/文字差分と統一パッチ",
            "reformat": "Nginx、Java、XML、HTML、JSON の整形", "json": "整形・圧縮・検証・パス照会", "java": "ローカルで JS/Python/Swift/Java を実行",
            "ymlProperties": "YAML・JSON・Properties 変換", "protobuf": "Protobuf wire とバイナリ", "variables": "プロセス環境と実行用変数",
            "http": "HTTP リクエストとレスポンス", "host": "Hosts の読み取りと編集", "net": "DNS、ping、whois、IF",
            "uaParse": "UA からブラウザ/OS/端末を推定", "encode": "Base64、URL、Hex など", "crypto": "ハッシュ、HMAC、AES、乱数",
            "regex": "正規表現のマッチと置換", "cron": "Cron 解析と次回実行", "qrCode": "QR コードの生成と読取",
            "timeConvert": "タイムスタンプとタイムゾーン", "messageBoard": "全画面メッセージ表示", "translation": "macOS 翻訳と単語帳",
            "calculator": "式・関数・基数変換", "colorBoard": "カラー選択と画面取色", "image": "画像のプレビューと変換",
            "pdf": "PDF プレビュー・結合・抽出", "hardware": "OS・CPU・メモリ・ディスク"
        ]
    ]

    private static let groupTable: [AppLanguage: [String: String]] = [
        .zhCN: ["home": "首页", "text": "笔记与文本", "dev": "开发与格式", "network": "网络与请求", "encode": "编码与加密", "daily": "实用工具", "system": "系统信息"],
        .enUS: ["home": "Home", "text": "Notes & Text", "dev": "Development & Format", "network": "Network & Requests", "encode": "Encoding & Crypto", "daily": "Utilities", "system": "System"],
        .jaJP: ["home": "ホーム", "text": "ノートとテキスト", "dev": "開発と整形", "network": "ネットワーク", "encode": "エンコードと暗号", "daily": "ユーティリティ", "system": "システム"]
    ]

    private static let ui: [AppLanguage: [String: String]] = [
        .zhCN: [
            "settings.language": "界面语言",
            "settings.autoCheckUpdates": "启动时检查更新",
            "app.nav.recent": "最近使用",
            "app.nav.search": "搜索",
            "app.nav.settings": "设置",
            "app.group.all": "全部工具",
            "app.search.title": "搜索工具",
            "app.search.placeholder": "搜索功能…",
            "update.available.title": "发现新版本",
            "update.upToDate": "当前已是最新版本。",
            "update.failed": "无法检查更新，请稍后重试或手动打开 GitHub Releases。",
            "update.openDownload": "打开下载页面",
            "update.later": "稍后",
            "tool.ready": "就绪",
            "editor.chars": "字符",
            "editor.paste": "粘贴",
            "editor.openFile": "打开文本文件",
            "editor.copy": "复制",
            "editor.export": "导出文本",
            "settings.category.sidebar": "侧边栏",
            "settings.category.proxy": "HTTP 代理",
            "settings.category.appearance": "外观",
            "settings.category.vault": "文档库 Git",
            "settings.category.migration": "数据迁移",
            "settings.category.backup": "工作区与备份",
            "settings.category.shortcuts": "快捷键",
            "settings.category.about": "关于",
            "settings.customGroups": "自定义分组",
            "settings.manageCustomGroups": "管理自定义分组…",
            "settings.hiddenNavTools": "侧栏隐藏工具",
            "settings.manageHiddenNav": "管理侧栏工具显示…",
            "settings.notConfigured": "未配置",
            "settings.none": "无",
            "settings.countUnit": "个",
            "settings.showGroupSeparators": "显示分组分隔线",
            "settings.showRecent": "显示最近使用",
            "settings.sidebarWidth": "侧栏宽度",
            "settings.trayEnabled": "启用菜单栏图标（托盘）",
            "settings.closeWindow": "关闭主窗口",
            "settings.close.ask": "每次询问",
            "settings.close.hide": "隐藏窗口",
            "settings.close.quit": "退出应用",
            "settings.autoDownloadPref": "有更新时自动下载（偏好）",
            "settings.proxyEnabled": "使用 HTTP 代理",
            "settings.host": "主机",
            "settings.port": "端口",
            "settings.usernameOptional": "用户名（可选）",
            "settings.passwordOptional": "密码（可选）",
            "tool.bigClock": "大时钟",
            "timeConvert.currentTime": "当前时间",
            "timeConvert.timestampSeconds": "时间戳（秒）",
            "timeConvert.localTimeZone": "本地时间 · %@",
            "timeConvert.timezone": "时区",
            "timeConvert.convert": "转换",
            "timeConvert.timestamp": "时间戳",
            "timeConvert.unit": "单位",
            "timeConvert.unitSecond": "秒",
            "timeConvert.unitMillisecond": "毫秒",
            "timeConvert.copy": "复制",
            "timeConvert.toLocal": "转为本地时间",
            "timeConvert.toTimestamp": "转为时间戳",
            "timeConvert.isoHint": "仍可在输入框使用 ISO 8601 或混合格式，通过下方「详细解析」查看秒/毫秒与 UTC。",
            "timeConvert.parseDetail": "详细解析（当前时间戳输入）",
            "timeConvert.statusToLocal": "已转为 %@ 本地时间",
            "timeConvert.statusToTimestamp": "已转为时间戳（%@）",
            "timeConvert.statusParsed": "已生成详细解析",
            "timeConvert.statusCopied": "已复制",
            "settings.theme": "主题",
            "settings.theme.system": "跟随系统",
            "settings.theme.light": "浅色",
            "settings.theme.dark": "深色",
            "settings.editorFontSize": "编辑器字号",
            "settings.wrapLines": "编辑器自动换行",
            "settings.vaultAutoCommit": "编辑空闲后自动创建检查点",
            "settings.importElectron": "从 Electron 导入工作台设置…",
            "migration.scan": "扫描",
            "migration.choose": "选择…",
            "migration.importLayout": "导入布局与代理…",
            "migration.importVaultDisk": "导入磁盘文档库…",
            "migration.importMerge": "合并导入…",
            "migration.electronStorePath": "Electron 数据文件",
            "migration.sqlitePath": "SQLite 数据库",
            "migration.section.java": "Java 版数据",
            "migration.section.sqlite": "HTTP 请求集合（SQLite）",
            "migration.scanJavaVaultDisk": "扫描磁盘文档库",
            "migration.importJavaVaultDisk": "导入 Java 磁盘文档库…",
            "migration.openFinder": "在 Finder 中打开…",
            "migration.importJavaHttp": "从 Java 数据库导入 HTTP…",
            "migration.mergeIntoWorkspace": "合并到当前原生工作区",
            "migration.intro": "从 next Electron 的 `mootool-next.json` 合并工作台布局、HTTP 代理、编辑器与文档库 Git 设置；并可从 Electron 磁盘目录 `quick-notes` / `json-vault` 导入文档与 `attachments/` 图片。SQLite 可合并 HTTP/Host/翻译/历史/草稿及表内文档正文；不含加密密钥。",
            "migration.preview.customGroups": "自定义分组",
            "migration.preview.hiddenTools": "隐藏侧栏工具",
            "migration.preview.paneKeys": "分栏键",
            "migration.preview.diskQuickNotes": "磁盘随手记",
            "migration.preview.diskJson": "磁盘 JSON",
            "migration.preview.diskImages": "磁盘图片",
            "migration.java.defaultDir": "默认目录",
            "migration.java.hintFound": "可从 `quick-notes` / `json-beauty` 磁盘目录或 SQLite 合并数据；完整遗留迁移服务仍以 Compose/Electron 为准。",
            "migration.java.hintMissing": "未在默认目录找到 Java 版数据库。若数据在其他位置，请用 Compose 迁移或手动复制文件到文档库。",
            "migration.preview.javaQuickNotes": "Java 磁盘随手记",
            "migration.preview.javaJson": "Java 磁盘 JSON",
            "migration.preview.javaImages": "Java 磁盘图片",
            "migration.sqlite.hint": "从 Electron/Java SQLite 合并 HTTP、Host、翻译、历史、草稿与文档库正文（`t_quick_note` / `t_json_beauty`）；重复标题+正文会跳过。",
            "migration.count.requests": "可导入请求",
            "migration.count.httpHistory": "可导入历史",
            "migration.count.host": "可导入 Host",
            "migration.count.translationWords": "可导入翻译词条",
            "migration.count.translationHistory": "可导入翻译历史",
            "migration.count.favorites": "可导入颜色/正则/Cron 收藏",
            "migration.count.funcHistory": "可导入通用工具历史",
            "migration.count.drafts": "可导入工具草稿",
            "migration.count.quickNotes": "可导入随手记文档",
            "migration.count.jsonDocs": "可导入 JSON 文档",
            "migration.confirm.settings.title": "导入 Electron 设置？",
            "migration.confirm.settings.message": "将覆盖匹配的工作台字段，并写入 HTTP 代理与编辑器偏好。导入前会自动保存当前工作区。",
            "migration.confirm.http.title": "导入 HTTP 请求集合？",
            "migration.confirm.http.message": "将合并 HTTP 集合、各工具历史（含 t_func_history）与 Host/翻译/收藏；重复项会跳过。",
            "migration.confirm.electronVault.title": "导入 Electron 磁盘文档库？",
            "migration.confirm.electronVault.message": "从 Electron 的 quick-notes 与 json-vault 目录复制文本文件；随手记正文中的 attachments/ 图片会转为原生附件。重复标题+正文会跳过。",
            "migration.confirm.javaVault.title": "导入 Java 磁盘文档库？",
            "migration.confirm.javaVault.message": "从 Java 版 `quick-notes` 与 `json-beauty` 目录合并文本与 attachments/ 图片；重复标题+正文会跳过。",
            "migration.panel.promptChoose": "选择",
            "migration.collection.java": "Java 导入",
            "migration.notice.settingsMerged": "已合并 Electron 工作台与网络/编辑器偏好。",
            "migration.notice.vaultImport": "%@ 磁盘文档库：随手记 +%d，JSON +%d，图片附件 +%d。",
            "migration.notice.sqliteImport": "请求 +%d；HTTP 历史 +%d；工具历史 +%d；草稿回写 %d；随手记 +%d；JSON +%d；Host +%d；词条 +%d；翻译历史 +%d；收藏 +%d。",
            "settings.version": "版本",
            "settings.tech": "技术",
            "settings.viewProject": "查看项目与反馈问题 ↗",
            "settings.productLine": "产品线",
            "settings.showInFinder": "在 Finder 中显示",
            "settings.exportBackup": "导出备份",
            "settings.importBackup": "导入备份…",
            "settings.hint.sidebarWidth": "在主窗口侧栏右缘拖动调整宽度，双击恢复默认 215 pt。",
            "settings.hint.tray": "与 Electron「系统托盘」相同：提供打开主窗口、设置、屏幕取色、区域截图、翻译与 Host 配置切换；不含自定义全局热键。",
            "settings.hint.closeBehavior": "关闭行为与 Electron `general.closeBehavior` 一致；自动下载偏好会随 Electron 设置迁移，原生版仍需在「检查更新」中手动获取安装包。",
            "settings.hint.proxy": "与 Electron 设置相同：HTTP / HTTPS 请求经此代理发送（含 HTTP 工具与网络诊断中的 HTTP 类调用）。不支持 SOCKS 与系统代理自动发现。",
            "settings.vault.idleCommit": "编辑空闲提交：%d 秒",
            "settings.vault.inactiveCommit": "窗口失焦提交：%d 秒",
            "settings.vault.autoPullOff": "自动 Pull：关闭",
            "settings.vault.autoPullEvery": "自动 Pull：每 %d 分钟",
            "settings.hint.vaultGit": "与 Electron 相同：在 JSON / 随手记文档库已初始化 Git 且编辑器已保存到工作区后，空闲或失焦时自动 commit；配置远程后会尝试 push。自动 Pull 仅在无本地未保存修改且工作区干净时执行。",
            "settings.hint.migration": "合并 Electron 工作台与代理/编辑器/语言偏好；SQLite 与磁盘 `quick-notes` / `json-vault` 可合并文档与附件。",
            "settings.hint.shortcuts": "与 Electron 设置页相同：只读展示主要快捷键（可从 Electron 设置迁移）；不提供自定义绑定或托盘全局热键。",
            "settings.hint.backup": "原生版拥有独立的应用标识、偏好设置与数据目录，可与 Java、Electron、Tauri 版同时安装。备份包含本产品工作区及已登记的图片附件；恢复前保存当前工作区和附件副本。",
            "settings.hint.about": "通过 GitHub Releases API 检查新版本；有更新时可打开下载页面。不含 Electron 安装包后台下载与静默安装。",
            "settings.restore.title": "恢复原生版工作区？",
            "settings.restore.confirm": "保存当前副本并恢复",
            "settings.restore.message": "备份包含 %d 份文档、%d 张图片和 %d 条历史记录。",
            "settings.error.workspaceBlocked": "当前工作区文件读取失败。请先在 Finder 中备份并处理原文件后重启，再导入备份。",
            "history.reformat.file": "文件",
            "history.reformat.text": "文本",
            "host.readSystem": "读取系统 Hosts",
            "host.validate": "检查配置",
            "host.export": "导出 hosts",
            "common.done": "完成",
            "history.restore": "恢复",
            "history.empty.title": "暂无历史记录",
            "history.empty.description": "运行工具后，结果会保存在这里。",
            "tray.open": "打开 MooTool",
            "tray.settings": "设置…",
            "tray.pickColor": "屏幕取色",
            "tray.screenshot": "区域截图",
            "tray.translate": "翻译",
            "tray.quit": "退出 MooTool",
            "color.choose": "选择颜色",
            "color.screenPick": "屏幕取色",
            "color.applyHex": "应用 HEX",
            "color.values": "颜色值",
            "color.hexInvalid": "请输入六位 HEX，如 #4F83CC。",
            "qr.correction": "纠错",
            "qr.savePng": "保存 PNG",
            "qr.recognizeImage": "识别图片…",
            "qr.recognizeResult": "识别结果",
            "qr.empty.title": "生成你的二维码",
            "qr.empty.description": "支持文本、网址和 Wi-Fi 配置信息",
            "qr.status.bytes": "%d bytes · 纠错 %@",
            "qr.status.found": "识别到 %d 个二维码",
            "image.screenshot": "截图",
            "image.format": "格式",
            "image.widthPlaceholder": "宽度 px",
            "image.export": "导出",
            "image.empty.title": "拖入一张图片",
            "image.empty.description": "支持 PNG、JPEG、HEIC、TIFF 等系统图像格式",
            "image.exportGroup": "导出",
            "image.quality": "质量",
            "image.watermarkPlaceholder": "文字水印（可选）",
            "pdf.pagesPlaceholder": "页码：1-3,5（留空为全部）",
            "pdf.export": "导出 PDF",
            "pdf.preview": "预览 PDF",
            "pdf.extractText": "提取文本",
            "pdf.mergeOrder": "合并顺序",
            "pdf.pageCount": "%d 页",
            "pdf.textTitle": "PDF 文本",
            "pdf.empty.title": "添加或拖入 PDF",
            "pdf.empty.description": "按左侧顺序合并，或按页码提取页面",
            "pdf.status.summary": "%d 份文件 · 共 %d 页",
            "textDiff.compare": "比较",
            "textDiff.clear": "清空",
            "textDiff.swap": "交换",
            "textDiff.copyDiff": "复制差异",
            "textDiff.prev": "上一处",
            "textDiff.next": "下一处",
            "textDiff.ignoreWhitespace": "忽略空白",
            "textDiff.highlight": "高亮",
            "textDiff.highlight.both": "行与字符",
            "textDiff.highlight.chars": "仅字符",
            "textDiff.highlight.lines": "仅行",
            "textDiff.view": "视图",
            "textDiff.view.side": "左右对比",
            "textDiff.view.unified": "统一差异",
            "textDiff.original": "原始文本",
            "textDiff.modified": "修改后",
            "textDiff.unifiedPane": "统一差异",
            "textDiff.charCount": "%d 字符",
            "textDiff.stats": "新增 %d · 删除 %d · 修改 %d",
            "textDiff.status.ready": "准备比较",
            "textDiff.status.enterText": "请输入文本",
            "textDiff.status.done": "比较完成 · %d 处差异",
            "textDiff.status.doneShort": "比较完成",
            "textDiff.status.cleared": "已清空",
            "textDiff.status.swapped": "已交换",
            "textDiff.status.noDiffCopy": "暂无可复制的差异",
            "textDiff.status.copied": "已复制统一差异",
            "textDiff.status.nav": "第 %d / %d 处差异",
            "reformat.mode": "工作方式",
            "reformat.tab.text": "文本格式化",
            "reformat.tab.file": "文件格式化",
            "reformat.type": "类型",
            "reformat.indent": "缩进",
            "reformat.indentSpaces": "%d 空格",
            "reformat.formatting": "正在格式化",
            "reformat.copyHelp": "复制当前内容",
            "reformat.exportHelp": "导出当前内容",
            "reformat.clearHelp": "清空当前内容",
            "reformat.openFile": "打开文件…",
            "reformat.fileHint": "选择 UTF-8 文本文件，最多 2 MB",
            "reformat.exportResult": "导出结果…",
            "reformat.fileOriginal": "原始文件",
            "reformat.fileResult": "格式化结果",
            "reformat.status.ready": "就绪 · 本地格式化",
            "reformat.error.empty": "请先输入内容或选择文件。",
            "reformat.status.done": "格式化完成 · %d 字符",
            "reformat.status.opened": "已打开 %@",
            "reformat.status.copied": "已复制当前内容",
            "reformat.status.cleared": "已清空",
            "palette.cancel": "取消",
            "palette.hint": "↑ ↓ 选择 · ↩ 打开 · Esc 关闭",
            "palette.count": "个工具",
            "settings.shortcut.search": "搜索工具",
            "settings.shortcut.settings": "打开设置",
            "settings.shortcut.saveVault": "JSON / 随手记保存",
            "settings.shortcut.formatJson": "JSON 格式化",
            "settings.shortcut.compareDiff": "文本对比比较",
            "settings.shortcut.formatTool": "格式化工具",
            "settings.shortcut.findReplace": "查找替换",
            "tool.input": "输入",
            "tool.output": "结果",
            "tool.run": "运行",
            "tool.example": "示例",
            "tool.clear": "清空输入和结果",
            "tool.format": "格式化",
            "tool.minify": "压缩",
            "tool.encode": "编码",
            "tool.decode": "解码",
            "tool.convert": "转换",
            "tool.now": "此刻",
            "tool.query": "查询",
            "tool.send": "发送",
            "workbench.search": "搜索工具",
            "workbench.pinned": "常用",
            "workbench.history": "历史记录",
            "workbench.detach": "独立窗口",
            "workbench.alert.title": "工作区提示",
            "workbench.alert.ok": "好",
            "workbench.pinHelp": "添加或移出常用工具",
            "workbench.sidebar.expand": "展开导航标题",
            "workbench.sidebar.iconsOnly": "仅显示图标",
            "workbench.settingsHelp": "设置 · ⌘,",
            "tool.runCode": "运行代码",
            "tool.stop": "停止",
            "tool.parse": "解析",
            "tool.translate": "翻译",
            "tool.fullscreen": "全屏展示",
            "tool.generateQr": "生成二维码",
            "tool.openImage": "打开图片",
            "tool.addPdf": "添加 PDF",
            "tool.newProfile": "新建配置",
            "tool.saveProfile": "保存配置",
            "tool.genKeyPair": "生成密钥对",
            "tool.digestText": "文本摘要",
            "tool.refreshSystemInfo": "刷新系统信息",
            "tool.refreshEnv": "查看当前环境",
            "tool.cronPreview": "预览执行时间",
            "tool.favorites": "收藏",
            "http.request": "请求",
            "http.response": "响应",
            "http.tab.params": "参数",
            "http.tab.headers": "请求头",
            "http.tab.cookies": "Cookie",
            "http.tab.body": "正文",
            "http.importCurl": "导入 cURL…",
            "http.copyCurl": "复制为 cURL",
            "http.saveToCollection": "保存到请求集合…",
            "http.openCollection": "打开请求集合…",
            "http.newRequest": "新建请求",
            "http.menuHelp": "cURL 与请求集合",
            "http.collection": "请求集合",
            "http.saveRequest": "保存当前请求",
            "http.cancelRequest": "取消请求",
            "http.followRedirects": "跟随重定向",
            "http.timeout": "超时",
            "http.seconds": "秒",
            "http.importCurlShort": "导入 cURL",
            "http.prettyJson": "JSON 格式化显示",
            "app.menu.about": "关于 MooTool Next Native",
            "app.menu.searchTools": "搜索工具…",
            "app.menu.checkUpdate": "检查更新…",
            "app.menu.tools": "工具",
            "translation.tab.translate": "翻译",
            "translation.tab.words": "词库",
            "translation.tab.history": "历史",
            "translation.applyToTranslate": "填入翻译页",
            "translation.source": "原文",
            "translation.target": "译文",
            "tool.new": "新建",
            "tool.save": "保存",
            "tool.delete": "删除",
            "translation.sourceAuto": "原文 · 自动识别语言",
            "translation.systemDictionary": "系统词典",
            "home.tagline": "开发与日常，得心应手。",
            "home.byAuthor": "由 Zhou Bo 创作",
            "home.section.about": "关于",
            "home.section.contributors": "贡献者",
            "home.section.sponsor": "赞赏",
            "home.section.source": "源码与反馈",
            "home.section.otherWorks": "其他作品",
            "home.aboutBody": "MooTool 是面向开发者与日常效率的桌面工具箱。原生版保留 26 个工具入口与工作区，数据独立保存在本机。",
            "home.contributorsThanks": "感谢每一位为 MooTool 生态贡献想法、代码与反馈的朋友。",
            "home.sponsorText": "如果 MooTool 对你有帮助，欢迎请作者喝杯咖啡。",
            "home.sponsorCaption": "微信赞赏码",
            "home.searchTools": "查找你需要的工具",
            "home.forMac.title": "为 Mac 而生",
            "home.forMac.body": "熟悉的 MooTool 工作方式，原生的 macOS 体验。通过侧边栏探索文本、开发、网络、编码和日常工具，也可以把工具单独打开，让工作区更从容。",
            "home.localSave": "本地保存",
            "home.standaloneInstall": "独立安装",
            "home.nativeShortcuts": "原生快捷键"
        ],
        .enUS: [
            "settings.language": "Language",
            "settings.autoCheckUpdates": "Check for updates on launch",
            "app.nav.recent": "Recent",
            "app.nav.search": "Search",
            "app.nav.settings": "Settings",
            "app.group.all": "All tools",
            "app.search.title": "Search tools",
            "app.search.placeholder": "Search tools…",
            "update.available.title": "Update available",
            "update.upToDate": "You are on the latest version.",
            "update.failed": "Could not check for updates. Try again later or open GitHub Releases.",
            "update.openDownload": "Open download page",
            "update.later": "Later",
            "tool.ready": "Ready",
            "editor.chars": "chars",
            "editor.paste": "Paste",
            "editor.openFile": "Open text file",
            "editor.copy": "Copy",
            "editor.export": "Export text",
            "settings.category.sidebar": "Sidebar",
            "settings.category.proxy": "HTTP Proxy",
            "settings.category.appearance": "Appearance",
            "settings.category.vault": "Vault Git",
            "settings.category.migration": "Data Migration",
            "settings.category.backup": "Workspace & Backup",
            "settings.category.shortcuts": "Shortcuts",
            "settings.category.about": "About",
            "settings.customGroups": "Custom groups",
            "settings.manageCustomGroups": "Manage custom groups…",
            "settings.hiddenNavTools": "Hidden sidebar tools",
            "settings.manageHiddenNav": "Manage sidebar visibility…",
            "settings.notConfigured": "Not configured",
            "settings.none": "None",
            "settings.countUnit": "",
            "settings.showGroupSeparators": "Show group separators",
            "settings.showRecent": "Show recent tools",
            "settings.sidebarWidth": "Sidebar width",
            "settings.trayEnabled": "Menu bar icon (tray)",
            "settings.closeWindow": "Close main window",
            "settings.close.ask": "Ask every time",
            "settings.close.hide": "Hide window",
            "settings.close.quit": "Quit app",
            "settings.autoDownloadPref": "Auto-download updates (preference)",
            "settings.proxyEnabled": "Use HTTP proxy",
            "settings.host": "Host",
            "settings.port": "Port",
            "settings.usernameOptional": "Username (optional)",
            "settings.passwordOptional": "Password (optional)",
            "tool.bigClock": "Large clock",
            "timeConvert.currentTime": "Current time",
            "timeConvert.timestampSeconds": "Timestamp (seconds)",
            "timeConvert.localTimeZone": "Local time · %@",
            "timeConvert.timezone": "Time zone",
            "timeConvert.convert": "Convert",
            "timeConvert.timestamp": "Timestamp",
            "timeConvert.unit": "Unit",
            "timeConvert.unitSecond": "Seconds",
            "timeConvert.unitMillisecond": "Milliseconds",
            "timeConvert.copy": "Copy",
            "timeConvert.toLocal": "To local time",
            "timeConvert.toTimestamp": "To timestamp",
            "timeConvert.isoHint": "You can still enter ISO 8601 or mixed formats; use Parse detail below for seconds, milliseconds, and UTC.",
            "timeConvert.parseDetail": "Parse detail (timestamp input)",
            "timeConvert.statusToLocal": "Converted to %@ local time",
            "timeConvert.statusToTimestamp": "Converted to timestamp (%@)",
            "timeConvert.statusParsed": "Detail output generated",
            "timeConvert.statusCopied": "Copied",
            "settings.theme": "Theme",
            "settings.theme.system": "System",
            "settings.theme.light": "Light",
            "settings.theme.dark": "Dark",
            "settings.editorFontSize": "Editor font size",
            "settings.wrapLines": "Wrap editor lines",
            "settings.vaultAutoCommit": "Auto-checkpoint after idle editing",
            "settings.importElectron": "Import from Electron…",
            "migration.scan": "Scan",
            "migration.choose": "Choose…",
            "migration.importLayout": "Import layout & proxy…",
            "migration.importVaultDisk": "Import vault folders…",
            "migration.importMerge": "Merge import…",
            "migration.electronStorePath": "Electron store file",
            "migration.sqlitePath": "SQLite database",
            "migration.section.java": "Java edition data",
            "migration.section.sqlite": "HTTP collections (SQLite)",
            "migration.scanJavaVaultDisk": "Scan vault folders",
            "migration.importJavaVaultDisk": "Import Java vault folders…",
            "migration.openFinder": "Reveal in Finder…",
            "migration.importJavaHttp": "Import HTTP from Java DB…",
            "migration.mergeIntoWorkspace": "Merge into workspace",
            "migration.intro": "Merge workbench layout, HTTP proxy, editor, and vault Git settings from Electron `mootool-next.json`; import documents and `attachments/` images from Electron `quick-notes` / `json-vault` folders. SQLite can merge HTTP/Host/translation/history/drafts and in-table note bodies; encryption keys are not imported.",
            "migration.preview.customGroups": "Custom groups",
            "migration.preview.hiddenTools": "Hidden sidebar tools",
            "migration.preview.paneKeys": "Pane keys",
            "migration.preview.diskQuickNotes": "Disk quick notes",
            "migration.preview.diskJson": "Disk JSON",
            "migration.preview.diskImages": "Disk images",
            "migration.java.defaultDir": "Default directory",
            "migration.java.hintFound": "Merge from `quick-notes` / `json-beauty` folders or SQLite; full legacy migration service remains in Compose/Electron.",
            "migration.java.hintMissing": "No Java database in the default directory. Use Compose migration or copy files manually if data lives elsewhere.",
            "migration.preview.javaQuickNotes": "Java disk quick notes",
            "migration.preview.javaJson": "Java disk JSON",
            "migration.preview.javaImages": "Java disk images",
            "migration.sqlite.hint": "Merge HTTP, Host, translation, history, drafts, and vault bodies (`t_quick_note` / `t_json_beauty`) from Electron/Java SQLite; duplicate title+body rows are skipped.",
            "migration.count.requests": "Importable requests",
            "migration.count.httpHistory": "Importable HTTP history",
            "migration.count.host": "Importable Host profiles",
            "migration.count.translationWords": "Importable translation words",
            "migration.count.translationHistory": "Importable translation history",
            "migration.count.favorites": "Importable color/regex/Cron favorites",
            "migration.count.funcHistory": "Importable tool history",
            "migration.count.drafts": "Importable tool drafts",
            "migration.count.quickNotes": "Importable quick notes",
            "migration.count.jsonDocs": "Importable JSON documents",
            "migration.confirm.settings.title": "Import Electron settings?",
            "migration.confirm.settings.message": "Matching workbench fields will be overwritten and HTTP proxy/editor preferences applied. The current workspace is saved before import.",
            "migration.confirm.http.title": "Import HTTP collections?",
            "migration.confirm.http.message": "Merges HTTP collections, tool history (including t_func_history), Host, translation, and favorites; duplicates are skipped.",
            "migration.confirm.electronVault.title": "Import Electron vault folders?",
            "migration.confirm.electronVault.message": "Copies text files from Electron quick-notes and json-vault; attachments/ in note bodies become native attachments. Duplicate title+body rows are skipped.",
            "migration.confirm.javaVault.title": "Import Java vault folders?",
            "migration.confirm.javaVault.message": "Merges text and attachments/ images from Java `quick-notes` and `json-beauty`; duplicate title+body rows are skipped.",
            "migration.panel.promptChoose": "Choose",
            "migration.collection.java": "Java import",
            "migration.notice.settingsMerged": "Electron workbench and network/editor preferences merged.",
            "migration.notice.vaultImport": "%@ vault folders: quick notes +%d, JSON +%d, attachments +%d.",
            "migration.notice.sqliteImport": "Requests +%d; HTTP history +%d; tool history +%d; drafts applied %d; quick notes +%d; JSON +%d; Host +%d; words +%d; translation history +%d; favorites +%d.",
            "settings.version": "Version",
            "settings.tech": "Technology",
            "settings.viewProject": "View project and issues ↗",
            "settings.productLine": "Product",
            "settings.showInFinder": "Reveal in Finder",
            "settings.exportBackup": "Export backup",
            "settings.importBackup": "Import backup…",
            "settings.hint.sidebarWidth": "Drag the main sidebar’s right edge to resize; double-click to reset to 215 pt.",
            "settings.hint.tray": "Same as Electron’s menu bar tray: open window, settings, screen color pick, region screenshot, translation, and Host profiles; no custom global hotkeys.",
            "settings.hint.closeBehavior": "Matches Electron `general.closeBehavior`; auto-download preference migrates from Electron, but you still fetch installers manually via Check for Updates.",
            "settings.hint.proxy": "Same as Electron: HTTP/HTTPS requests use this proxy (HTTP tool and HTTP-style network diagnostics). SOCKS and system proxy discovery are not supported.",
            "settings.vault.idleCommit": "Idle commit: %d s",
            "settings.vault.inactiveCommit": "Inactive commit: %d s",
            "settings.vault.autoPullOff": "Auto pull: off",
            "settings.vault.autoPullEvery": "Auto pull: every %d min",
            "settings.hint.vaultGit": "Same as Electron: auto-commit when JSON/Quick Note vault Git is initialized and the editor is saved; push when a remote is configured. Auto pull runs only with a clean, saved workspace.",
            "settings.hint.migration": "Merge Electron workbench, proxy, editor, and language; SQLite and disk `quick-notes` / `json-vault` can merge documents and attachments.",
            "settings.hint.shortcuts": "Read-only shortcut reference like Electron settings (can migrate from Electron); no custom bindings or tray global hotkeys.",
            "settings.hint.backup": "Separate app ID, preferences, and data directory from Java, Electron, and Tauri builds. Backups include the workspace and registered images; save a copy before restore.",
            "settings.hint.about": "Checks GitHub Releases API; opens the download page when an update exists. No background download or silent install.",
            "settings.restore.title": "Restore native workspace?",
            "settings.restore.confirm": "Save copy and restore",
            "settings.restore.message": "Backup contains %d documents, %d images, and %d history entries.",
            "settings.error.workspaceBlocked": "Cannot read the workspace file. Back it up in Finder, fix the file, restart, then import the backup.",
            "history.reformat.file": "File",
            "history.reformat.text": "Text",
            "host.readSystem": "Read system hosts",
            "host.validate": "Validate profile",
            "host.export": "Export hosts",
            "common.done": "Done",
            "history.restore": "Restore",
            "history.empty.title": "No history yet",
            "history.empty.description": "Results appear here after you run the tool.",
            "tray.open": "Open MooTool",
            "tray.settings": "Settings…",
            "tray.pickColor": "Screen color picker",
            "tray.screenshot": "Region screenshot",
            "tray.translate": "Translation",
            "tray.quit": "Quit MooTool",
            "color.choose": "Pick color",
            "color.screenPick": "Sample screen",
            "color.applyHex": "Apply HEX",
            "color.values": "Color values",
            "color.hexInvalid": "Enter a 6-digit HEX value, e.g. #4F83CC.",
            "qr.correction": "Correction",
            "qr.savePng": "Save PNG",
            "qr.recognizeImage": "Recognize image…",
            "qr.recognizeResult": "Recognition",
            "qr.empty.title": "Generate a QR code",
            "qr.empty.description": "Text, URLs, and Wi‑Fi configuration strings",
            "qr.status.bytes": "%d bytes · correction %@",
            "qr.status.found": "Recognized %d QR code(s)",
            "image.screenshot": "Screenshot",
            "image.format": "Format",
            "image.widthPlaceholder": "Width px",
            "image.export": "Export",
            "image.empty.title": "Drop an image",
            "image.empty.description": "PNG, JPEG, HEIC, TIFF, and other system image formats",
            "image.exportGroup": "Export",
            "image.quality": "Quality",
            "image.watermarkPlaceholder": "Text watermark (optional)",
            "pdf.pagesPlaceholder": "Pages: 1-3,5 (empty = all)",
            "pdf.export": "Export PDF",
            "pdf.preview": "Preview PDF",
            "pdf.extractText": "Extract text",
            "pdf.mergeOrder": "Merge order",
            "pdf.pageCount": "%d pages",
            "pdf.textTitle": "PDF text",
            "pdf.empty.title": "Add or drop PDFs",
            "pdf.empty.description": "Merge in list order or extract pages by range",
            "pdf.status.summary": "%d files · %d pages total",
            "textDiff.compare": "Compare",
            "textDiff.clear": "Clear",
            "textDiff.swap": "Swap",
            "textDiff.copyDiff": "Copy diff",
            "textDiff.prev": "Previous",
            "textDiff.next": "Next",
            "textDiff.ignoreWhitespace": "Ignore whitespace",
            "textDiff.highlight": "Highlight",
            "textDiff.highlight.both": "Lines & chars",
            "textDiff.highlight.chars": "Characters only",
            "textDiff.highlight.lines": "Lines only",
            "textDiff.view": "View",
            "textDiff.view.side": "Side by side",
            "textDiff.view.unified": "Unified diff",
            "textDiff.original": "Original",
            "textDiff.modified": "Modified",
            "textDiff.unifiedPane": "Unified diff",
            "textDiff.charCount": "%d chars",
            "textDiff.stats": "+%d · −%d · ~%d",
            "textDiff.status.ready": "Ready to compare",
            "textDiff.status.enterText": "Enter text to compare",
            "textDiff.status.done": "Compared · %d change(s)",
            "textDiff.status.doneShort": "Compared",
            "textDiff.status.cleared": "Cleared",
            "textDiff.status.swapped": "Swapped",
            "textDiff.status.noDiffCopy": "Nothing to copy",
            "textDiff.status.copied": "Unified diff copied",
            "textDiff.status.nav": "Change %d / %d",
            "reformat.mode": "Mode",
            "reformat.tab.text": "Format text",
            "reformat.tab.file": "Format file",
            "reformat.type": "Type",
            "reformat.indent": "Indent",
            "reformat.indentSpaces": "%d spaces",
            "reformat.formatting": "Formatting",
            "reformat.copyHelp": "Copy current content",
            "reformat.exportHelp": "Export current content",
            "reformat.clearHelp": "Clear current content",
            "reformat.openFile": "Open file…",
            "reformat.fileHint": "Choose a UTF-8 text file (max 2 MB)",
            "reformat.exportResult": "Export result…",
            "reformat.fileOriginal": "Original file",
            "reformat.fileResult": "Formatted result",
            "reformat.status.ready": "Ready · local formatting",
            "reformat.error.empty": "Enter content or choose a file first.",
            "reformat.status.done": "Formatted · %d characters",
            "reformat.status.opened": "Opened %@",
            "reformat.status.copied": "Copied current content",
            "reformat.status.cleared": "Cleared",
            "palette.cancel": "Cancel",
            "palette.hint": "↑ ↓ select · ↩ open · Esc close",
            "palette.count": "tools",
            "settings.shortcut.search": "Search tools",
            "settings.shortcut.settings": "Open settings",
            "settings.shortcut.saveVault": "Save JSON / Quick Note",
            "settings.shortcut.formatJson": "Format JSON",
            "settings.shortcut.compareDiff": "Compare text diff",
            "settings.shortcut.formatTool": "Reformat tool",
            "settings.shortcut.findReplace": "Find and replace",
            "tool.input": "Input",
            "tool.output": "Output",
            "tool.run": "Run",
            "tool.example": "Example",
            "tool.clear": "Clear input and output",
            "tool.format": "Format",
            "tool.minify": "Minify",
            "tool.encode": "Encode",
            "tool.decode": "Decode",
            "tool.convert": "Convert",
            "tool.now": "Now",
            "tool.query": "Query",
            "tool.send": "Send",
            "workbench.search": "Search tools",
            "workbench.pinned": "Pinned",
            "workbench.history": "History",
            "workbench.detach": "Detach window",
            "workbench.alert.title": "Workspace notice",
            "workbench.alert.ok": "OK",
            "workbench.pinHelp": "Pin or unpin this tool",
            "workbench.sidebar.expand": "Show navigation titles",
            "workbench.sidebar.iconsOnly": "Icons only",
            "workbench.settingsHelp": "Settings · ⌘,",
            "tool.runCode": "Run code",
            "tool.stop": "Stop",
            "tool.parse": "Parse",
            "tool.translate": "Translate",
            "tool.fullscreen": "Fullscreen",
            "tool.generateQr": "Generate QR",
            "tool.openImage": "Open image",
            "tool.addPdf": "Add PDF",
            "tool.newProfile": "New profile",
            "tool.saveProfile": "Save profile",
            "tool.genKeyPair": "Generate key pair",
            "tool.digestText": "Digest text",
            "tool.refreshSystemInfo": "Refresh system info",
            "tool.refreshEnv": "View environment",
            "tool.cronPreview": "Preview schedule",
            "tool.favorites": "Favorites",
            "http.request": "Request",
            "http.response": "Response",
            "http.tab.params": "Params",
            "http.tab.headers": "Headers",
            "http.tab.cookies": "Cookies",
            "http.tab.body": "Body",
            "http.importCurl": "Import cURL…",
            "http.copyCurl": "Copy as cURL",
            "http.saveToCollection": "Save to collection…",
            "http.openCollection": "Open collection…",
            "http.newRequest": "New request",
            "http.menuHelp": "cURL and collections",
            "http.collection": "Collection",
            "http.saveRequest": "Save request",
            "http.cancelRequest": "Cancel",
            "http.followRedirects": "Follow redirects",
            "http.timeout": "Timeout",
            "http.seconds": "s",
            "http.importCurlShort": "Import cURL",
            "http.prettyJson": "Pretty-print JSON",
            "app.menu.about": "About MooTool Next Native",
            "app.menu.searchTools": "Search Tools…",
            "app.menu.checkUpdate": "Check for Updates…",
            "app.menu.tools": "Tools",
            "translation.tab.translate": "Translate",
            "translation.tab.words": "Word book",
            "translation.tab.history": "History",
            "translation.applyToTranslate": "Use in translate tab",
            "translation.source": "Source",
            "translation.target": "Translation",
            "tool.new": "New",
            "tool.save": "Save",
            "tool.delete": "Delete",
            "translation.sourceAuto": "Source · auto-detect",
            "translation.systemDictionary": "System dictionary",
            "home.tagline": "Development and daily tasks, at hand.",
            "home.byAuthor": "By Zhou Bo",
            "home.section.about": "About",
            "home.section.contributors": "Contributors",
            "home.section.sponsor": "Sponsor",
            "home.section.source": "Source & feedback",
            "home.section.otherWorks": "More projects",
            "home.aboutBody": "MooTool is a desktop toolbox for developers and everyday productivity. Native keeps 26 tool entries and an independent on-device workspace.",
            "home.contributorsThanks": "Thanks to everyone who contributes ideas, code, and feedback to MooTool.",
            "home.sponsorText": "If MooTool helps you, consider buying the author a coffee.",
            "home.sponsorCaption": "WeChat tip QR",
            "home.searchTools": "Find a tool",
            "home.forMac.title": "Built for Mac",
            "home.forMac.body": "The familiar MooTool workflow with a native macOS experience. Explore text, dev, network, encoding, and daily tools in the sidebar—or open tools in their own windows.",
            "home.localSave": "On-device data",
            "home.standaloneInstall": "Standalone install",
            "home.nativeShortcuts": "Native shortcuts"
        ],
        .jaJP: [
            "settings.language": "表示言語",
            "settings.autoCheckUpdates": "起動時に更新を確認",
            "app.nav.recent": "最近",
            "app.nav.search": "検索",
            "app.nav.settings": "設定",
            "app.group.all": "すべてのツール",
            "app.search.title": "ツールを検索",
            "app.search.placeholder": "ツールを検索…",
            "update.available.title": "新しいバージョンがあります",
            "update.upToDate": "最新バージョンです。",
            "update.failed": "更新を確認できませんでした。後でもう一度試すか GitHub Releases を開いてください。",
            "update.openDownload": "ダウンロードページを開く",
            "update.later": "後で",
            "tool.ready": "準備完了",
            "editor.chars": "文字",
            "editor.paste": "貼り付け",
            "editor.openFile": "テキストを開く",
            "editor.copy": "コピー",
            "editor.export": "テキストを書き出す",
            "settings.category.sidebar": "サイドバー",
            "settings.category.proxy": "HTTP プロキシ",
            "settings.category.appearance": "外観",
            "settings.category.vault": "ドキュメント Git",
            "settings.category.migration": "データ移行",
            "settings.category.backup": "ワークスペースとバックアップ",
            "settings.category.shortcuts": "ショートカット",
            "settings.category.about": "情報",
            "settings.customGroups": "カスタムグループ",
            "settings.manageCustomGroups": "カスタムグループを管理…",
            "settings.hiddenNavTools": "非表示のサイドバーツール",
            "settings.manageHiddenNav": "サイドバーの表示を管理…",
            "settings.notConfigured": "未設定",
            "settings.none": "なし",
            "settings.countUnit": "件",
            "settings.showGroupSeparators": "グループ区切りを表示",
            "settings.showRecent": "最近使ったツールを表示",
            "settings.sidebarWidth": "サイドバー幅",
            "settings.trayEnabled": "メニューバーアイコン（トレイ）",
            "settings.closeWindow": "メインウィンドウを閉じる",
            "settings.close.ask": "毎回確認",
            "settings.close.hide": "ウィンドウを隠す",
            "settings.close.quit": "アプリを終了",
            "settings.autoDownloadPref": "更新を自動ダウンロード（設定）",
            "settings.proxyEnabled": "HTTP プロキシを使用",
            "settings.host": "ホスト",
            "settings.port": "ポート",
            "settings.usernameOptional": "ユーザー名（任意）",
            "settings.passwordOptional": "パスワード（任意）",
            "tool.bigClock": "大きな時計",
            "timeConvert.currentTime": "現在時刻",
            "timeConvert.timestampSeconds": "タイムスタンプ（秒）",
            "timeConvert.localTimeZone": "ローカル時刻 · %@",
            "timeConvert.timezone": "タイムゾーン",
            "timeConvert.convert": "変換",
            "timeConvert.timestamp": "タイムスタンプ",
            "timeConvert.unit": "単位",
            "timeConvert.unitSecond": "秒",
            "timeConvert.unitMillisecond": "ミリ秒",
            "timeConvert.copy": "コピー",
            "timeConvert.toLocal": "ローカル時刻に変換",
            "timeConvert.toTimestamp": "タイムスタンプに変換",
            "timeConvert.isoHint": "入力欄では ISO 8601 や混在形式も利用できます。下の「詳細解析」で秒/ミリ秒と UTC を確認できます。",
            "timeConvert.parseDetail": "詳細解析（タイムスタンプ入力）",
            "timeConvert.statusToLocal": "%@ のローカル時刻に変換しました",
            "timeConvert.statusToTimestamp": "タイムスタンプ（%@）に変換しました",
            "timeConvert.statusParsed": "詳細解析を生成しました",
            "timeConvert.statusCopied": "コピーしました",
            "settings.theme": "テーマ",
            "settings.theme.system": "システムに合わせる",
            "settings.theme.light": "ライト",
            "settings.theme.dark": "ダーク",
            "settings.editorFontSize": "エディタの文字サイズ",
            "settings.wrapLines": "エディタで折り返し",
            "settings.vaultAutoCommit": "編集アイドル後に自動チェックポイント",
            "settings.importElectron": "Electron からインポート…",
            "migration.scan": "スキャン",
            "migration.choose": "選択…",
            "migration.importLayout": "レイアウトとプロキシをインポート…",
            "migration.importVaultDisk": "ディスクのドキュメントをインポート…",
            "migration.importMerge": "マージしてインポート…",
            "migration.electronStorePath": "Electron データファイル",
            "migration.sqlitePath": "SQLite データベース",
            "migration.section.java": "Java 版データ",
            "migration.section.sqlite": "HTTP コレクション（SQLite）",
            "migration.scanJavaVaultDisk": "ディスクをスキャン",
            "migration.importJavaVaultDisk": "Java ディスクをインポート…",
            "migration.openFinder": "Finder で表示…",
            "migration.importJavaHttp": "Java DB から HTTP をインポート…",
            "migration.mergeIntoWorkspace": "ワークスペースにマージ",
            "migration.intro": "Electron の `mootool-next.json` からワークベンチレイアウト、HTTP プロキシ、エディタ、ドキュメント Git 設定をマージ。Electron の `quick-notes` / `json-vault` から本文と `attachments/` 画像もインポート。SQLite では HTTP/Host/翻訳/履歴/下書きと表内本文をマージ（暗号鍵は含みません）。",
            "migration.preview.customGroups": "カスタムグループ",
            "migration.preview.hiddenTools": "非表示のサイドバーツール",
            "migration.preview.paneKeys": "ペインキー",
            "migration.preview.diskQuickNotes": "ディスクのクイックノート",
            "migration.preview.diskJson": "ディスク JSON",
            "migration.preview.diskImages": "ディスク画像",
            "migration.java.defaultDir": "既定ディレクトリ",
            "migration.java.hintFound": "`quick-notes` / `json-beauty` または SQLite からマージ可能。完全なレガシー移行は Compose/Electron を利用してください。",
            "migration.java.hintMissing": "既定ディレクトリに Java 版 DB が見つかりません。別の場所にある場合は Compose 移行または手動コピーを利用してください。",
            "migration.preview.javaQuickNotes": "Java ディスクのクイックノート",
            "migration.preview.javaJson": "Java ディスク JSON",
            "migration.preview.javaImages": "Java ディスク画像",
            "migration.sqlite.hint": "Electron/Java SQLite から HTTP、Host、翻訳、履歴、下書き、本文（`t_quick_note` / `t_json_beauty`）をマージ。同じタイトル+本文はスキップ。",
            "migration.count.requests": "インポート可能なリクエスト",
            "migration.count.httpHistory": "インポート可能な履歴",
            "migration.count.host": "インポート可能な Host",
            "migration.count.translationWords": "インポート可能な翻訳語",
            "migration.count.translationHistory": "インポート可能な翻訳履歴",
            "migration.count.favorites": "インポート可能な色/正規表現/Cron お気に入り",
            "migration.count.funcHistory": "インポート可能なツール履歴",
            "migration.count.drafts": "インポート可能なツール下書き",
            "migration.count.quickNotes": "インポート可能なクイックノート",
            "migration.count.jsonDocs": "インポート可能な JSON ドキュメント",
            "migration.confirm.settings.title": "Electron 設定をインポートしますか？",
            "migration.confirm.settings.message": "一致するワークベンチ項目を上書きし、HTTP プロキシとエディタ設定を適用します。インポート前に現在のワークスペースを保存します。",
            "migration.confirm.http.title": "HTTP コレクションをインポートしますか？",
            "migration.confirm.http.message": "HTTP コレクション、ツール履歴（t_func_history 含む）、Host、翻訳、お気に入りをマージ。重複はスキップ。",
            "migration.confirm.electronVault.title": "Electron ディスクドキュメントをインポートしますか？",
            "migration.confirm.electronVault.message": "Electron の quick-notes と json-vault からテキストをコピー。本文の attachments/ はネイティブ添付に変換。同じタイトル+本文はスキップ。",
            "migration.confirm.javaVault.title": "Java ディスクドキュメントをインポートしますか？",
            "migration.confirm.javaVault.message": "Java の `quick-notes` と `json-beauty` から本文と attachments/ 画像をマージ。同じタイトル+本文はスキップ。",
            "migration.panel.promptChoose": "選択",
            "migration.collection.java": "Java インポート",
            "migration.notice.settingsMerged": "Electron ワークベンチとネットワーク/エディタ設定をマージしました。",
            "migration.notice.vaultImport": "%@ ディスク：クイックノート +%d、JSON +%d、添付 +%d。",
            "migration.notice.sqliteImport": "リクエスト +%d；HTTP 履歴 +%d；ツール履歴 +%d；下書き適用 %d；クイックノート +%d；JSON +%d；Host +%d；語 +%d；翻訳履歴 +%d；お気に入り +%d。",
            "settings.version": "バージョン",
            "settings.tech": "技術",
            "settings.viewProject": "プロジェクトと Issue ↗",
            "settings.productLine": "プロダクト",
            "settings.showInFinder": "Finder で表示",
            "settings.exportBackup": "バックアップを書き出す",
            "settings.importBackup": "バックアップを読み込む…",
            "settings.hint.sidebarWidth": "メインサイドバー右端をドラッグして幅を変更。ダブルクリックで既定 215 pt に戻します。",
            "settings.hint.tray": "Electron のメニューバーと同様：ウィンドウ、設定、画面取色、範囲スクリーンショット、翻訳、Host 切替（グローバルホットキーはなし）。",
            "settings.hint.closeBehavior": "Electron の `general.closeBehavior` と同じ。自動ダウンロード設定は移行できますが、インストーラは「更新を確認」から手動取得。",
            "settings.hint.proxy": "Electron と同じ：HTTP/HTTPS はこのプロキシ経由（HTTP ツールと HTTP 系ネットワーク診断）。SOCKS とシステムプロキシ自動検出は非対応。",
            "settings.vault.idleCommit": "アイドル時コミット：%d 秒",
            "settings.vault.inactiveCommit": "非アクティブ時コミット：%d 秒",
            "settings.vault.autoPullOff": "自動 Pull：オフ",
            "settings.vault.autoPullEvery": "自動 Pull：%d 分ごと",
            "settings.hint.vaultGit": "Electron と同じ：JSON/クイックノートの Git 初期化後、保存済みエディタはアイドル/非アクティブで自動 commit。リモート設定時は push。自動 Pull は未保存変更がなくクリーンなときのみ。",
            "settings.hint.migration": "Electron ワークベンチ、プロキシ、エディタ、言語をマージ。SQLite とディスク `quick-notes` / `json-vault` で本文と添付をマージ可能。",
            "settings.hint.shortcuts": "Electron 設定と同様の読み取り専用ショートカット（Electron から移行可）。カスタム割り当てとトレイグローバルホットキーはなし。",
            "settings.hint.backup": "Java/Electron/Tauri と別のアプリ ID・設定・データディレクトリ。バックアップはワークスペースと登録画像を含みます。復元前にコピーを保存してください。",
            "settings.hint.about": "GitHub Releases API で更新を確認。更新がある場合はダウンロードページを開きます。バックグラウンドダウンロードとサイレントインストールはなし。",
            "settings.restore.title": "ネイティブワークスペースを復元しますか？",
            "settings.restore.confirm": "現在のコピーを保存して復元",
            "settings.restore.message": "バックアップ：ドキュメント %d、画像 %d、履歴 %d 件。",
            "settings.error.workspaceBlocked": "ワークスペースファイルを読み取れません。Finder でバックアップし、ファイルを修正して再起動後にインポートしてください。",
            "history.reformat.file": "ファイル",
            "history.reformat.text": "テキスト",
            "host.readSystem": "システム Hosts を読み込む",
            "host.validate": "プロファイルを検証",
            "host.export": "hosts を書き出す",
            "common.done": "完了",
            "history.restore": "復元",
            "history.empty.title": "履歴がありません",
            "history.empty.description": "ツールを実行すると、ここに結果が保存されます。",
            "tray.open": "MooTool を開く",
            "tray.settings": "設定…",
            "tray.pickColor": "画面から色を取得",
            "tray.screenshot": "範囲スクリーンショット",
            "tray.translate": "翻訳",
            "tray.quit": "MooTool を終了",
            "color.choose": "色を選択",
            "color.screenPick": "画面から取色",
            "color.applyHex": "HEX を適用",
            "color.values": "色の値",
            "color.hexInvalid": "6 桁の HEX を入力してください（例：#4F83CC）。",
            "qr.correction": "誤り訂正",
            "qr.savePng": "PNG を保存",
            "qr.recognizeImage": "画像を認識…",
            "qr.recognizeResult": "認識結果",
            "qr.empty.title": "QR コードを生成",
            "qr.empty.description": "テキスト、URL、Wi‑Fi 設定など",
            "qr.status.bytes": "%d bytes · 誤り訂正 %@",
            "qr.status.found": "%d 件の QR コードを認識",
            "image.screenshot": "スクリーンショット",
            "image.format": "形式",
            "image.widthPlaceholder": "幅 px",
            "image.export": "書き出す",
            "image.empty.title": "画像をドロップ",
            "image.empty.description": "PNG、JPEG、HEIC、TIFF などの画像形式",
            "image.exportGroup": "書き出し",
            "image.quality": "品質",
            "image.watermarkPlaceholder": "文字ウォーターマーク（任意）",
            "pdf.pagesPlaceholder": "ページ：1-3,5（空欄はすべて）",
            "pdf.export": "PDF を書き出す",
            "pdf.preview": "PDF をプレビュー",
            "pdf.extractText": "テキストを抽出",
            "pdf.mergeOrder": "結合順",
            "pdf.pageCount": "%d ページ",
            "pdf.textTitle": "PDF テキスト",
            "pdf.empty.title": "PDF を追加またはドロップ",
            "pdf.empty.description": "左の順序で結合、またはページ範囲で抽出",
            "pdf.status.summary": "%d ファイル · 合計 %d ページ",
            "textDiff.compare": "比較",
            "textDiff.clear": "クリア",
            "textDiff.swap": "入れ替え",
            "textDiff.copyDiff": "差分をコピー",
            "textDiff.prev": "前へ",
            "textDiff.next": "次へ",
            "textDiff.ignoreWhitespace": "空白を無視",
            "textDiff.highlight": "強調",
            "textDiff.highlight.both": "行と文字",
            "textDiff.highlight.chars": "文字のみ",
            "textDiff.highlight.lines": "行のみ",
            "textDiff.view": "表示",
            "textDiff.view.side": "左右比較",
            "textDiff.view.unified": "統一差分",
            "textDiff.original": "元のテキスト",
            "textDiff.modified": "変更後",
            "textDiff.unifiedPane": "統一差分",
            "textDiff.charCount": "%d 文字",
            "textDiff.stats": "追加 %d · 削除 %d · 変更 %d",
            "textDiff.status.ready": "比較の準備完了",
            "textDiff.status.enterText": "テキストを入力してください",
            "textDiff.status.done": "比較完了 · %d 件の差分",
            "textDiff.status.doneShort": "比較完了",
            "textDiff.status.cleared": "クリアしました",
            "textDiff.status.swapped": "入れ替えました",
            "textDiff.status.noDiffCopy": "コピーできる差分がありません",
            "textDiff.status.copied": "統一差分をコピーしました",
            "textDiff.status.nav": "差分 %d / %d",
            "reformat.mode": "モード",
            "reformat.tab.text": "テキスト整形",
            "reformat.tab.file": "ファイル整形",
            "reformat.type": "種類",
            "reformat.indent": "インデント",
            "reformat.indentSpaces": "%d スペース",
            "reformat.formatting": "整形中",
            "reformat.copyHelp": "現在の内容をコピー",
            "reformat.exportHelp": "現在の内容を書き出す",
            "reformat.clearHelp": "現在の内容をクリア",
            "reformat.openFile": "ファイルを開く…",
            "reformat.fileHint": "UTF-8 テキスト（最大 2 MB）を選択",
            "reformat.exportResult": "結果を書き出す…",
            "reformat.fileOriginal": "元のファイル",
            "reformat.fileResult": "整形結果",
            "reformat.status.ready": "準備完了 · ローカル整形",
            "reformat.error.empty": "内容を入力するかファイルを選択してください。",
            "reformat.status.done": "整形完了 · %d 文字",
            "reformat.status.opened": "%@ を開きました",
            "reformat.status.copied": "現在の内容をコピーしました",
            "reformat.status.cleared": "クリアしました",
            "palette.cancel": "キャンセル",
            "palette.hint": "↑ ↓ 選択 · ↩ 開く · Esc 閉じる",
            "palette.count": "件のツール",
            "settings.shortcut.search": "ツールを検索",
            "settings.shortcut.settings": "設定を開く",
            "settings.shortcut.saveVault": "JSON / クイックノートを保存",
            "settings.shortcut.formatJson": "JSON を整形",
            "settings.shortcut.compareDiff": "テキスト比較",
            "settings.shortcut.formatTool": "整形ツール",
            "settings.shortcut.findReplace": "検索と置換",
            "tool.input": "入力",
            "tool.output": "結果",
            "tool.run": "実行",
            "tool.example": "例",
            "tool.clear": "入力と結果をクリア",
            "tool.format": "整形",
            "tool.minify": "圧縮",
            "tool.encode": "エンコード",
            "tool.decode": "デコード",
            "tool.convert": "変換",
            "tool.now": "現在",
            "tool.query": "照会",
            "tool.send": "送信",
            "workbench.search": "ツールを検索",
            "workbench.pinned": "ピン留め",
            "workbench.history": "履歴",
            "workbench.detach": "別ウィンドウ",
            "workbench.alert.title": "ワークスペース",
            "workbench.alert.ok": "OK",
            "workbench.pinHelp": "ピン留めの追加/解除",
            "workbench.sidebar.expand": "ナビのタイトルを表示",
            "workbench.sidebar.iconsOnly": "アイコンのみ",
            "workbench.settingsHelp": "設定 · ⌘,",
            "tool.runCode": "コードを実行",
            "tool.stop": "停止",
            "tool.parse": "解析",
            "tool.translate": "翻訳",
            "tool.fullscreen": "全画面表示",
            "tool.generateQr": "QR を生成",
            "tool.openImage": "画像を開く",
            "tool.addPdf": "PDF を追加",
            "tool.newProfile": "新規プロファイル",
            "tool.saveProfile": "プロファイルを保存",
            "tool.genKeyPair": "鍵ペアを生成",
            "tool.digestText": "テキストを要約",
            "tool.refreshSystemInfo": "システム情報を更新",
            "tool.refreshEnv": "環境を表示",
            "tool.cronPreview": "実行予定をプレビュー",
            "tool.favorites": "お気に入り",
            "http.request": "リクエスト",
            "http.response": "レスポンス",
            "http.tab.params": "パラメータ",
            "http.tab.headers": "ヘッダー",
            "http.tab.cookies": "Cookie",
            "http.tab.body": "本文",
            "http.importCurl": "cURL をインポート…",
            "http.copyCurl": "cURL としてコピー",
            "http.saveToCollection": "コレクションに保存…",
            "http.openCollection": "コレクションを開く…",
            "http.newRequest": "新規リクエスト",
            "http.menuHelp": "cURL とコレクション",
            "http.collection": "コレクション",
            "http.saveRequest": "リクエストを保存",
            "http.cancelRequest": "キャンセル",
            "http.followRedirects": "リダイレクトを追従",
            "http.timeout": "タイムアウト",
            "http.seconds": "秒",
            "http.importCurlShort": "cURL をインポート",
            "http.prettyJson": "JSON を整形表示",
            "app.menu.about": "MooTool Next Native について",
            "app.menu.searchTools": "ツールを検索…",
            "app.menu.checkUpdate": "更新を確認…",
            "app.menu.tools": "ツール",
            "translation.tab.translate": "翻訳",
            "translation.tab.words": "単語帳",
            "translation.tab.history": "履歴",
            "translation.applyToTranslate": "翻訳タブに入力",
            "translation.source": "原文",
            "translation.target": "訳文",
            "tool.new": "新規",
            "tool.save": "保存",
            "tool.delete": "削除",
            "translation.sourceAuto": "原文 · 言語自動",
            "translation.systemDictionary": "システム辞書",
            "home.tagline": "開発も日常も、手のひらに。",
            "home.byAuthor": "Zhou Bo 作",
            "home.section.about": "概要",
            "home.section.contributors": "コントリビューター",
            "home.section.sponsor": "支援",
            "home.section.source": "ソースとフィードバック",
            "home.section.otherWorks": "その他の作品",
            "home.aboutBody": "MooTool は開発者と日常の効率向けのデスクトップツールボックスです。ネイティブ版は 26 ツールと独立したローカルワークスペースを提供します。",
            "home.contributorsThanks": "MooTool エコシステムに貢献してくださる皆さんに感謝します。",
            "home.sponsorText": "MooTool が役に立ったら、作者にコーヒーを一杯どうぞ。",
            "home.sponsorCaption": "WeChat チップ QR",
            "home.searchTools": "ツールを探す",
            "home.forMac.title": "Mac のために",
            "home.forMac.body": "おなじみの MooTool の使い方を、ネイティブ macOS 体験で。サイドバーでテキスト・開発・ネットワーク・エンコード・日常ツールを探索し、ツールを別ウィンドウで開くこともできます。",
            "home.localSave": "ローカル保存",
            "home.standaloneInstall": "独立インストール",
            "home.nativeShortcuts": "ネイティブショートカット"
        ]
    ]
}

public extension Tool {
    func localized(in language: AppLanguage) -> Tool {
        Tool(
            id,
            AppLocalization.toolTitle(id, language: language),
            symbol,
            AppLocalization.groupTitle(group, language: language),
            AppLocalization.toolSubtitle(id, language: language, fallback: subtitle),
            keywords)
    }
}

public extension Catalog {
    static func localizedTools(_ language: AppLanguage) -> [Tool] {
        tools.map { $0.localized(in: language) }
    }

    static func localizedTool(_ id: String, language: AppLanguage) -> Tool {
        tool(id).localized(in: language)
    }
}
