import { contextBridge, ipcRenderer, type IpcRendererEvent } from 'electron'
import type {
  AppNavigationEvent,
  AppPaths,
  ExternalPageId,
  RuntimeStatus,
  ToolId,
  ToolWindowSnapshot,
  ToolWindowStatus,
  ToolWorkspaceBounds,
  WorkspaceState
} from '../../src/shared/contracts/app'
import type { AppSettings, SecretKey, SecretStatus, SettingsPatch } from '../../src/shared/contracts/settings'
import type { FuncHistoryRecord, HistoryQuery, SaveFuncHistoryInput } from '../../src/shared/contracts/history'
import type { SaveTextFileInput, TextFileKind, TextFileResult } from '../../src/shared/contracts/files'
import type { ImageAsset, ImageAssetSummary, RenameImageAssetInput, SaveImageAssetInput, ScreenCapture } from '../../src/shared/contracts/images'
import type { DigestAlgorithmId, DigestFileResult, ImageFilePayload, SaveBinaryFileInput } from '../../src/shared/contracts/nativeFiles'
import type { PdfFileInfo, PdfMergeSource, PdfOperationResult, PdfSplitTask } from '../../src/shared/contracts/pdf'
import type { JsonVaultFile, JsonVaultListInput, JsonVaultNode, MoveJsonVaultEntryInput, RenameJsonVaultEntryInput, SaveJsonVaultFileInput } from '../../src/shared/contracts/jsonVault'
import type { CreateQuickNoteInput, MoveQuickNoteEntryInput, QuickNoteAttachment, QuickNoteFile, QuickNoteListInput, QuickNoteNode, RenameQuickNoteEntryInput, SaveQuickNoteInput } from '../../src/shared/contracts/quickNote'
import type { VaultGitActionInput, VaultGitActionResult, VaultGitCommit, VaultGitDiffInput, VaultGitStatus } from '../../src/shared/contracts/vaultGit'
import type { FavoriteKind, FavoriteRecord, SaveFavoriteInput } from '../../src/shared/contracts/favorites'
import type { HttpRequestDraft, HttpRequestHistory, HttpResponseResult, HttpSendInput, SaveTranslationHistoryInput, SaveTranslationWordInput, SavedHttpRequest, TranslationHistory, TranslationInput, TranslationResult, TranslationWord } from '../../src/shared/contracts/network'
import type { EnvironmentSnapshot, HostProfile, LocalAddressSnapshot, NetworkCommandInput, NetworkCommandResult, SaveHostProfileInput, SystemHostsFile, SystemInfoSnapshot } from '../../src/shared/contracts/system'
import type { RuntimeExecutionInput, RuntimeExecutionResult, RuntimeOutputEvent } from '../../src/shared/contracts/runtime'
import type { BackupExportResult, BackupInfo, BackupKind, BackupLocation } from '../../src/shared/contracts/backup'
import type { LegacyMigrationInput, LegacyMigrationPreview, LegacyMigrationResult } from '../../src/shared/contracts/migration'
import type { UpdateCheckEvent, UpdateCheckResult, UpdateDownloadState } from '../../src/shared/contracts/update'
import type { AiDiscoveryInput, AiDoctorSnapshot } from '../../src/shared/contracts/ai'
import type { AiChangeApplyResult, AiChangePlan, AiChangeRollbackResult } from '../../src/shared/contracts/aiChanges'
import type { AiSkillInstallApplyInput, AiSkillInstallApplyResult, AiSkillInstallInput, AiSkillInstallPreview, AiSkillInstallRollbackResult } from '../../src/shared/contracts/aiSkills'
import type { AiInstructionPreview, AiInstructionPreviewInput } from '../../src/shared/contracts/aiInstructions'
import type { AiMcpCopyInput, AiMcpCopyPreview, AiMcpInventory, AiMcpInventoryInput, AiMcpProbeInput, AiMcpProbeResult } from '../../src/shared/contracts/aiMcp'
import type { AiMemory, AiMemoryCandidate, AiMemoryCandidateReviewInput, AiMemoryCandidateSaveInput, AiMemoryListInput, AiMemoryPreview, AiMemoryPreviewInput, AiMemorySaveInput, AiMemorySnapshot } from '../../src/shared/contracts/aiMemory'
import type { AiModelRuntimeDetailInput, AiModelRuntimeModelDetail, AiModelRuntimeSnapshot } from '../../src/shared/contracts/aiModelRuntime'
import type { AiUsageBudget, AiUsageBudgetInput, AiUsageDashboard, AiUsageDashboardInput, AiUsageExportInput, AiUsageExportResult, AiUsageImportPreview, AiUsageImportPreviewInput, AiUsageImportResult, AiUsageProviderSyncInput, AiUsageProviderSyncResult } from '../../src/shared/contracts/aiUsage'
import type { AiAgentLaunchPlan, AiAgentManagerInput, AiAgentManagerSnapshot, AiAgentProfile, AiAgentProfileSaveInput } from '../../src/shared/contracts/aiAgents'
import type { AiContextInspectorInput, AiContextInspectorSnapshot } from '../../src/shared/contracts/aiContext'
import type { AiPromptLabRunInput, AiPromptLabRunResult, AiPromptLabSuite, AiPromptLabSuiteSaveInput } from '../../src/shared/contracts/aiPromptLab'
import type { AiAgentProfileShareDocument } from '../../src/shared/contracts/aiAgentShare'
import type { AiProjectStarterPreview, AiProjectStarterPreviewInput } from '../../src/shared/contracts/aiProjectStarter'
import type { AiAgentTaskOutputEvent, AiAgentTaskResult, AiAgentTaskStartInput } from '../../src/shared/contracts/aiAgentTasks'
import type { AiModelRuntimeActionExecuteInput, AiModelRuntimeActionPlan, AiModelRuntimeActionPlanInput, AiModelRuntimeActionProgressEvent, AiModelRuntimeActionResult } from '../../src/shared/contracts/aiModelRuntimeActions'
import type { AiNativeMemorySnapshot } from '../../src/shared/contracts/aiNativeMemory'
import type { AiMemoryEmbeddingProgressEvent, AiMemoryEmbeddingRebuildInput, AiMemoryEmbeddingRebuildResult, AiMemoryEmbeddingStatus, AiMemorySemanticPreview, AiMemorySemanticPreviewInput } from '../../src/shared/contracts/aiMemoryEmbedding'

contextBridge.exposeInMainWorld('mootool', {
  platform: process.platform,
  toolWindowsEnabled: process.env.NODE_ENV !== 'test' || process.env.MOOTOOL_TOOL_VIEWS === '1',
  getAppVersion: (): Promise<string> => ipcRenderer.invoke('app:get-version'),
  getAppPaths: (): Promise<AppPaths> => ipcRenderer.invoke('app:get-paths'),
  getSystemTheme: (): Promise<'light' | 'dark'> => ipcRenderer.invoke('theme:get-system'),
  getSettings: (): Promise<AppSettings> => ipcRenderer.invoke('settings:get'),
  updateSettings: (patch: SettingsPatch): Promise<AppSettings> => ipcRenderer.invoke('settings:update', patch),
  openSettings: (): Promise<void> => ipcRenderer.invoke('settings:open'),
  closeSettings: (): Promise<void> => ipcRenderer.invoke('settings:close'),
  dismissWindow: (): Promise<void> => ipcRenderer.invoke('window:dismiss'),
  getSecretStatus: (key: SecretKey): Promise<SecretStatus> => ipcRenderer.invoke('secret:status', key),
  setSecret: (key: SecretKey, value: string): Promise<SecretStatus> => ipcRenderer.invoke('secret:set', key, value),
  clearSecret: (key: SecretKey): Promise<SecretStatus> => ipcRenderer.invoke('secret:clear', key),
  getWorkspaceState: (): Promise<WorkspaceState> => ipcRenderer.invoke('workspace:get'),
  setWorkspaceState: (state: WorkspaceState): Promise<WorkspaceState> => ipcRenderer.invoke('workspace:set', state),
  getToolWindowSnapshot: (): Promise<ToolWindowSnapshot> => ipcRenderer.invoke('tool-window:snapshot'),
  activateToolView: (toolId: ToolId): Promise<ToolWindowSnapshot> => ipcRenderer.invoke('tool-window:activate', toolId),
  setToolWorkspaceBounds: (bounds: ToolWorkspaceBounds): Promise<ToolWindowSnapshot> => ipcRenderer.invoke('tool-window:set-workspace-bounds', bounds),
  getToolWindowState: (toolId: Exclude<ToolId, 'mootool'>): Promise<ToolWindowStatus> => ipcRenderer.invoke('tool-window:get-state', toolId),
  detachToolWindow: (toolId: Exclude<ToolId, 'mootool'>): Promise<ToolWindowStatus> => ipcRenderer.invoke('tool-window:detach', toolId),
  dockToolWindow: (toolId: Exclude<ToolId, 'mootool'>): Promise<ToolWindowStatus> => ipcRenderer.invoke('tool-window:dock', toolId),
  focusToolWindow: (toolId: Exclude<ToolId, 'mootool'>): Promise<boolean> => ipcRenderer.invoke('tool-window:focus', toolId),
  setToolWindowTitle: (toolId: Exclude<ToolId, 'mootool'>, title: string): Promise<void> => ipcRenderer.invoke('tool-window:set-title', toolId, title),
  listHistory: (query: HistoryQuery): Promise<FuncHistoryRecord[]> => ipcRenderer.invoke('history:list', query),
  saveHistory: (input: SaveFuncHistoryInput): Promise<void> => ipcRenderer.invoke('history:save', input),
  deleteHistory: (id: number): Promise<void> => ipcRenderer.invoke('history:delete', id),
  clearHistory: (funcType: string): Promise<void> => ipcRenderer.invoke('history:clear', funcType),
  listFavorites: (kind: FavoriteKind): Promise<FavoriteRecord[]> => ipcRenderer.invoke('favorite:list', kind),
  saveFavorite: (input: SaveFavoriteInput): Promise<FavoriteRecord> => ipcRenderer.invoke('favorite:save', input),
  deleteFavorite: (id: number): Promise<void> => ipcRenderer.invoke('favorite:delete', id),
  listHttpRequests: (keyword?: string): Promise<SavedHttpRequest[]> => ipcRenderer.invoke('http:list', keyword),
  saveHttpRequest: (request: HttpRequestDraft, response?: HttpResponseResult): Promise<SavedHttpRequest> => ipcRenderer.invoke('http:save', request, response),
  deleteHttpRequest: (id: number): Promise<void> => ipcRenderer.invoke('http:delete', id),
  listHttpHistory: (keyword?: string): Promise<HttpRequestHistory[]> => ipcRenderer.invoke('http:history-list', keyword),
  deleteHttpHistory: (id: number): Promise<void> => ipcRenderer.invoke('http:history-delete', id),
  clearHttpHistory: (): Promise<void> => ipcRenderer.invoke('http:history-clear'),
  sendHttpRequest: (input: HttpSendInput): Promise<HttpResponseResult> => ipcRenderer.invoke('http:send', input),
  cancelNetworkRequest: (requestId: string): Promise<boolean> => ipcRenderer.invoke('network:cancel', requestId),
  translate: (input: TranslationInput): Promise<TranslationResult> => ipcRenderer.invoke('translation:send', input),
  listTranslationWords: (keyword?: string): Promise<TranslationWord[]> => ipcRenderer.invoke('translation:words-list', keyword),
  saveTranslationWord: (input: SaveTranslationWordInput): Promise<TranslationWord> => ipcRenderer.invoke('translation:words-save', input),
  deleteTranslationWord: (id: number): Promise<void> => ipcRenderer.invoke('translation:words-delete', id),
  listTranslationHistory: (keyword?: string): Promise<TranslationHistory[]> => ipcRenderer.invoke('translation:history-list', keyword),
  saveTranslationHistory: (input: SaveTranslationHistoryInput): Promise<TranslationHistory> => ipcRenderer.invoke('translation:history-save', input),
  deleteTranslationHistory: (id: number): Promise<void> => ipcRenderer.invoke('translation:history-delete', id),
  clearTranslationHistory: (): Promise<void> => ipcRenderer.invoke('translation:history-clear'),
  listHostProfiles: (keyword?: string): Promise<HostProfile[]> => ipcRenderer.invoke('host:list', keyword),
  saveHostProfile: (input: SaveHostProfileInput): Promise<HostProfile> => ipcRenderer.invoke('host:save', input),
  deleteHostProfile: (id: number): Promise<void> => ipcRenderer.invoke('host:delete', id),
  readSystemHosts: (): Promise<SystemHostsFile> => ipcRenderer.invoke('host:read-system'),
  writeSystemHosts: (content: string): Promise<SystemHostsFile> => ipcRenderer.invoke('host:write-system', content),
  runNetworkCommand: (input: NetworkCommandInput): Promise<NetworkCommandResult> => ipcRenderer.invoke('system:network-command', input),
  cancelSystemCommand: (requestId: string): Promise<boolean> => ipcRenderer.invoke('system:cancel', requestId),
  getEnvironmentSnapshot: (): Promise<EnvironmentSnapshot> => ipcRenderer.invoke('system:environment'),
  getLocalAddresses: (): Promise<LocalAddressSnapshot> => ipcRenderer.invoke('system:local-addresses'),
  getSystemInfo: (): Promise<SystemInfoSnapshot> => ipcRenderer.invoke('system:info'),
  chooseDirectory: (initialPath?: string): Promise<string | null> => ipcRenderer.invoke('dialog:choose-directory', initialPath),
  openTextFile: (kind: TextFileKind): Promise<TextFileResult | null> => ipcRenderer.invoke('files:open-text', kind),
  saveTextFile: (input: SaveTextFileInput): Promise<string | null> => ipcRenderer.invoke('files:save-text', input),
  digestFile: (algorithm: DigestAlgorithmId): Promise<DigestFileResult | null> => ipcRenderer.invoke('files:digest', algorithm),
  chooseImageFile: (): Promise<ImageFilePayload | null> => ipcRenderer.invoke('files:choose-image'),
  saveBinaryFile: (input: SaveBinaryFileInput): Promise<string | null> => ipcRenderer.invoke('files:save-binary', input),
  readClipboardImage: (): Promise<string | null> => ipcRenderer.invoke('clipboard:read-image'),
  writeClipboardImage: (dataUrl: string): Promise<void> => ipcRenderer.invoke('clipboard:write-image', dataUrl),
  captureScreens: (): Promise<ScreenCapture[]> => ipcRenderer.invoke('screen:capture'),
  listImageAssets: (): Promise<ImageAssetSummary[]> => ipcRenderer.invoke('images:list'),
  readImageAsset: (name: string): Promise<ImageAsset> => ipcRenderer.invoke('images:read', name),
  importImageAssets: (): Promise<ImageAssetSummary[]> => ipcRenderer.invoke('images:import'),
  saveImageAsset: (input: SaveImageAssetInput): Promise<ImageAssetSummary> => ipcRenderer.invoke('images:save', input),
  renameImageAsset: (input: RenameImageAssetInput): Promise<ImageAssetSummary> => ipcRenderer.invoke('images:rename', input),
  deleteImageAssets: (names: string[]): Promise<void> => ipcRenderer.invoke('images:delete', names),
  exportImageAssets: (names: string[]): Promise<string | null> => ipcRenderer.invoke('images:export', names),
  openImageAsset: (name: string): Promise<void> => ipcRenderer.invoke('images:open', name),
  choosePdfFiles: (): Promise<PdfFileInfo[]> => ipcRenderer.invoke('pdf:choose-files'),
  mergePdfFiles: (sources: PdfMergeSource[]): Promise<PdfOperationResult | null> => ipcRenderer.invoke('pdf:merge', sources),
  splitPdfFiles: (tasks: PdfSplitTask[]): Promise<PdfOperationResult> => ipcRenderer.invoke('pdf:split', tasks),
  listJsonVault: (input?: JsonVaultListInput): Promise<JsonVaultNode[]> => ipcRenderer.invoke('json-vault:list', input),
  readJsonVaultFile: (relativePath: string): Promise<JsonVaultFile> => ipcRenderer.invoke('json-vault:read', relativePath),
  saveJsonVaultFile: (input: SaveJsonVaultFileInput): Promise<JsonVaultFile> => ipcRenderer.invoke('json-vault:save', input),
  createJsonVaultFolder: (relativePath: string): Promise<string> => ipcRenderer.invoke('json-vault:create-folder', relativePath),
  renameJsonVaultEntry: (input: RenameJsonVaultEntryInput): Promise<string> => ipcRenderer.invoke('json-vault:rename', input),
  moveJsonVaultEntry: (input: MoveJsonVaultEntryInput): Promise<string> => ipcRenderer.invoke('json-vault:move', input),
  duplicateJsonVaultFile: (relativePath: string): Promise<JsonVaultFile> => ipcRenderer.invoke('json-vault:duplicate', relativePath),
  deleteJsonVaultFile: (relativePath: string): Promise<void> => ipcRenderer.invoke('json-vault:delete', relativePath),
  openJsonVault: (): Promise<void> => ipcRenderer.invoke('json-vault:open'),
  setJsonVaultEditorDirty: (dirty: boolean): Promise<void> => ipcRenderer.invoke('json-vault:set-editor-dirty', dirty),
  getVaultGitStatus: (): Promise<VaultGitStatus> => ipcRenderer.invoke('vault-git:status'),
  listVaultGitHistory: (): Promise<VaultGitCommit[]> => ipcRenderer.invoke('vault-git:history'),
  getVaultGitDiff: (input: VaultGitDiffInput): Promise<string> => ipcRenderer.invoke('vault-git:diff', input),
  runVaultGitAction: (input: VaultGitActionInput): Promise<VaultGitActionResult> => ipcRenderer.invoke('vault-git:action', input),
  listQuickNotes: (input?: QuickNoteListInput): Promise<QuickNoteNode[]> => ipcRenderer.invoke('quick-note:list', input),
  readQuickNote: (relativePath: string): Promise<QuickNoteFile> => ipcRenderer.invoke('quick-note:read', relativePath),
  createQuickNote: (input: CreateQuickNoteInput): Promise<QuickNoteFile> => ipcRenderer.invoke('quick-note:create', input),
  saveQuickNote: (input: SaveQuickNoteInput): Promise<QuickNoteFile> => ipcRenderer.invoke('quick-note:save', input),
  createQuickNoteFolder: (relativePath: string): Promise<string> => ipcRenderer.invoke('quick-note:create-folder', relativePath),
  renameQuickNoteEntry: (input: RenameQuickNoteEntryInput): Promise<string> => ipcRenderer.invoke('quick-note:rename', input),
  moveQuickNoteEntry: (input: MoveQuickNoteEntryInput): Promise<string> => ipcRenderer.invoke('quick-note:move', input),
  duplicateQuickNote: (relativePath: string): Promise<QuickNoteFile> => ipcRenderer.invoke('quick-note:duplicate', relativePath),
  deleteQuickNoteEntry: (relativePath: string): Promise<void> => ipcRenderer.invoke('quick-note:delete', relativePath),
  importQuickNoteAttachment: (): Promise<QuickNoteAttachment | null> => ipcRenderer.invoke('quick-note:import-attachment'),
  readQuickNoteAttachment: (relativePath: string): Promise<string> => ipcRenderer.invoke('quick-note:read-attachment', relativePath),
  openQuickNoteVault: (): Promise<void> => ipcRenderer.invoke('quick-note:open-vault'),
  setQuickNoteEditorDirty: (dirty: boolean): Promise<void> => ipcRenderer.invoke('quick-note:set-editor-dirty', dirty),
  getQuickNoteGitStatus: (): Promise<VaultGitStatus> => ipcRenderer.invoke('quick-note-git:status'),
  listQuickNoteGitHistory: (): Promise<VaultGitCommit[]> => ipcRenderer.invoke('quick-note-git:history'),
  getQuickNoteGitDiff: (input: VaultGitDiffInput): Promise<string> => ipcRenderer.invoke('quick-note-git:diff', input),
  runQuickNoteGitAction: (input: VaultGitActionInput): Promise<VaultGitActionResult> => ipcRenderer.invoke('quick-note-git:action', input),
  getBackupInfo: (): Promise<BackupInfo> => ipcRenderer.invoke('backup:info'),
  exportBackup: (kind: BackupKind): Promise<BackupExportResult | null> => ipcRenderer.invoke('backup:export', kind),
  openBackupLocation: (location: BackupLocation): Promise<void> => ipcRenderer.invoke('backup:open-location', location),
  getDefaultLegacySource: (): Promise<string> => ipcRenderer.invoke('legacy-migration:default-source'),
  previewLegacyMigration: (input: LegacyMigrationInput): Promise<LegacyMigrationPreview> => ipcRenderer.invoke('legacy-migration:preview', input),
  runLegacyMigration: (input: LegacyMigrationInput): Promise<LegacyMigrationResult> => ipcRenderer.invoke('legacy-migration:run', input),
  checkForUpdates: (): Promise<UpdateCheckResult> => ipcRenderer.invoke('update:check'),
  getUpdateState: (): Promise<UpdateDownloadState> => ipcRenderer.invoke('update:get-state'),
  downloadUpdate: (): Promise<UpdateDownloadState> => ipcRenderer.invoke('update:download'),
  installUpdate: (): Promise<void> => ipcRenderer.invoke('update:install'),
  openReleasePage: (): Promise<void> => ipcRenderer.invoke('update:open-release'),
  openProjectPage: (): Promise<void> => ipcRenderer.invoke('app:open-project'),
  openExternalPage: (pageId: ExternalPageId): Promise<void> => ipcRenderer.invoke('app:open-external', pageId),
  detectRuntimes: (): Promise<RuntimeStatus[]> => ipcRenderer.invoke('runtime:detect'),
  runCode: (input: RuntimeExecutionInput): Promise<RuntimeExecutionResult> => ipcRenderer.invoke('runtime:run', input),
  cancelCodeRun: (requestId: string): Promise<boolean> => ipcRenderer.invoke('runtime:cancel', requestId),
  scanAiEnvironment: (input?: AiDiscoveryInput): Promise<AiDoctorSnapshot> => ipcRenderer.invoke('ai:scan', input),
  getAiModelRuntimeSnapshot: (): Promise<AiModelRuntimeSnapshot> => ipcRenderer.invoke('ai:model-runtime:snapshot'),
  inspectAiModelRuntimeModel: (input: AiModelRuntimeDetailInput): Promise<AiModelRuntimeModelDetail> => ipcRenderer.invoke('ai:model-runtime:inspect-model', input),
  planAiModelRuntimeAction: (input: AiModelRuntimeActionPlanInput): Promise<AiModelRuntimeActionPlan> => ipcRenderer.invoke('ai:model-runtime:plan-action', input),
  executeAiModelRuntimeAction: (input: AiModelRuntimeActionExecuteInput): Promise<AiModelRuntimeActionResult> => ipcRenderer.invoke('ai:model-runtime:execute-action', input),
  cancelAiModelRuntimeAction: (requestId: string): Promise<boolean> => ipcRenderer.invoke('ai:model-runtime:cancel-action', requestId),
  listAiPromptLabSuites: (): Promise<AiPromptLabSuite[]> => ipcRenderer.invoke('ai:prompt-lab:list'),
  saveAiPromptLabSuite: (input: AiPromptLabSuiteSaveInput): Promise<AiPromptLabSuite> => ipcRenderer.invoke('ai:prompt-lab:save', input),
  deleteAiPromptLabSuite: (id: string): Promise<void> => ipcRenderer.invoke('ai:prompt-lab:delete', id),
  runAiPromptLab: (input: AiPromptLabRunInput): Promise<AiPromptLabRunResult> => ipcRenderer.invoke('ai:prompt-lab:run', input),
  cancelAiPromptLab: (requestId: string): Promise<boolean> => ipcRenderer.invoke('ai:prompt-lab:cancel', requestId),
  previewAiProjectStarter: (input: AiProjectStarterPreviewInput): Promise<AiProjectStarterPreview> => ipcRenderer.invoke('ai:project-starter:preview', input),
  applyAiProjectStarter: (planId: string): Promise<AiChangeApplyResult> => ipcRenderer.invoke('ai:project-starter:apply', planId),
  rollbackAiProjectStarter: (snapshotId: string): Promise<AiChangeRollbackResult> => ipcRenderer.invoke('ai:project-starter:rollback', snapshotId),
  getAiUsageDashboard: (input: AiUsageDashboardInput): Promise<AiUsageDashboard> => ipcRenderer.invoke('ai:usage:dashboard', input),
  chooseAiUsageFiles: (): Promise<string[]> => ipcRenderer.invoke('ai:usage:choose-files'),
  previewAiUsageImport: (input: AiUsageImportPreviewInput): Promise<AiUsageImportPreview> => ipcRenderer.invoke('ai:usage:preview-import', input),
  applyAiUsageImport: (planId: string, timezoneOffsetMinutes: number): Promise<AiUsageImportResult> => ipcRenderer.invoke('ai:usage:apply-import', planId, timezoneOffsetMinutes),
  saveAiUsageBudget: (input: AiUsageBudgetInput): Promise<AiUsageBudget> => ipcRenderer.invoke('ai:usage:save-budget', input),
  syncAiUsageProvider: (input: AiUsageProviderSyncInput): Promise<AiUsageProviderSyncResult> => ipcRenderer.invoke('ai:usage:sync-provider', input),
  clearAiUsage: (): Promise<number> => ipcRenderer.invoke('ai:usage:clear'),
  exportAiUsage: (input: AiUsageExportInput): Promise<AiUsageExportResult | null> => ipcRenderer.invoke('ai:usage:export', input),
  getAiAgentManagerSnapshot: (input?: AiAgentManagerInput): Promise<AiAgentManagerSnapshot> => ipcRenderer.invoke('ai:agents:snapshot', input),
  saveAiAgentProfile: (input: AiAgentProfileSaveInput): Promise<AiAgentProfile> => ipcRenderer.invoke('ai:agents:save-profile', input),
  deleteAiAgentProfile: (id: string): Promise<void> => ipcRenderer.invoke('ai:agents:delete-profile', id),
  getAiAgentLaunchPlan: (id: string): Promise<AiAgentLaunchPlan> => ipcRenderer.invoke('ai:agents:launch-plan', id),
  runAiAgentTask: (input: AiAgentTaskStartInput): Promise<AiAgentTaskResult> => ipcRenderer.invoke('ai:agents:run-task', input),
  cancelAiAgentTask: (requestId: string): Promise<boolean> => ipcRenderer.invoke('ai:agents:cancel-task', requestId),
  exportAiAgentProfile: (id: string): Promise<string | null> => ipcRenderer.invoke('ai:agents:export-profile', id),
  importAiAgentProfile: (): Promise<AiAgentProfileShareDocument | null> => ipcRenderer.invoke('ai:agents:import-profile'),
  inspectAiContext: (input: AiContextInspectorInput): Promise<AiContextInspectorSnapshot> => ipcRenderer.invoke('ai:context:inspect', input),
  previewClaudeCompatibilityEntry: (projectRoot: string): Promise<AiChangePlan> => ipcRenderer.invoke('ai:instructions:preview-claude-entry', projectRoot),
  applyClaudeCompatibilityEntry: (planId: string): Promise<AiChangeApplyResult> => ipcRenderer.invoke('ai:instructions:apply-claude-entry', planId),
  rollbackClaudeCompatibilityEntry: (snapshotId: string): Promise<AiChangeRollbackResult> => ipcRenderer.invoke('ai:instructions:rollback-claude-entry', snapshotId),
  previewEffectiveInstructions: (input: AiInstructionPreviewInput): Promise<AiInstructionPreview> => ipcRenderer.invoke('ai:instructions:preview-effective', input),
  previewSkillInstall: (input: AiSkillInstallInput): Promise<AiSkillInstallPreview> => ipcRenderer.invoke('ai:skills:preview-install', input),
  applySkillInstall: (input: AiSkillInstallApplyInput): Promise<AiSkillInstallApplyResult> => ipcRenderer.invoke('ai:skills:apply-install', input),
  rollbackSkillInstall: (snapshotId: string): Promise<AiSkillInstallRollbackResult> => ipcRenderer.invoke('ai:skills:rollback-install', snapshotId),
  getMcpInventory: (input?: AiMcpInventoryInput): Promise<AiMcpInventory> => ipcRenderer.invoke('ai:mcp:inventory', input),
  previewMcpCopy: (input: AiMcpCopyInput): Promise<AiMcpCopyPreview> => ipcRenderer.invoke('ai:mcp:preview-copy', input),
  applyMcpCopy: (planId: string): Promise<AiChangeApplyResult> => ipcRenderer.invoke('ai:mcp:apply-copy', planId),
  rollbackMcpCopy: (snapshotId: string): Promise<AiChangeRollbackResult> => ipcRenderer.invoke('ai:mcp:rollback-copy', snapshotId),
  probeMcpServer: (input: AiMcpProbeInput): Promise<AiMcpProbeResult> => ipcRenderer.invoke('ai:mcp:probe', input),
  cancelMcpProbe: (requestId: string): Promise<boolean> => ipcRenderer.invoke('ai:mcp:cancel-probe', requestId),
  getAiMemorySnapshot: (input?: AiMemoryListInput): Promise<AiMemorySnapshot> => ipcRenderer.invoke('ai:memory:snapshot', input),
  getAiNativeMemorySnapshot: (): Promise<AiNativeMemorySnapshot> => ipcRenderer.invoke('ai:memory:native-snapshot'),
  getAiMemoryEmbeddingStatus: (): Promise<AiMemoryEmbeddingStatus> => ipcRenderer.invoke('ai:memory:embedding-status'),
  rebuildAiMemoryEmbeddings: (input: AiMemoryEmbeddingRebuildInput): Promise<AiMemoryEmbeddingRebuildResult> => ipcRenderer.invoke('ai:memory:rebuild-embeddings', input),
  previewAiMemoriesSemantic: (input: AiMemorySemanticPreviewInput): Promise<AiMemorySemanticPreview> => ipcRenderer.invoke('ai:memory:semantic-preview', input),
  cancelAiMemoryEmbedding: (requestId: string): Promise<boolean> => ipcRenderer.invoke('ai:memory:cancel-embedding', requestId),
  saveAiMemory: (input: AiMemorySaveInput): Promise<AiMemory> => ipcRenderer.invoke('ai:memory:save', input),
  archiveAiMemory: (id: string): Promise<AiMemory> => ipcRenderer.invoke('ai:memory:archive', id),
  restoreAiMemory: (id: string): Promise<AiMemory> => ipcRenderer.invoke('ai:memory:restore', id),
  deleteAiMemory: (id: string): Promise<void> => ipcRenderer.invoke('ai:memory:delete', id),
  createAiMemoryCandidate: (input: AiMemoryCandidateSaveInput): Promise<AiMemoryCandidate> => ipcRenderer.invoke('ai:memory:create-candidate', input),
  reviewAiMemoryCandidate: (input: AiMemoryCandidateReviewInput): Promise<AiMemoryCandidate> => ipcRenderer.invoke('ai:memory:review-candidate', input),
  previewAiMemories: (input: AiMemoryPreviewInput): Promise<AiMemoryPreview> => ipcRenderer.invoke('ai:memory:preview', input),
  onSystemThemeChange: (callback: (theme: 'light' | 'dark') => void) => subscribe('theme:system-changed', callback),
  onSettingsChange: (callback: (settings: AppSettings) => void) => subscribe('settings:changed', callback),
  onSettingsNavigate: (callback: (category: string) => void) => subscribe('settings:navigate', callback),
  onNavigate: (callback: (event: AppNavigationEvent) => void) => subscribe('app:navigate', callback),
  onToolWindowSnapshotChange: (callback: (snapshot: ToolWindowSnapshot) => void) => subscribe('tool-window:snapshot-changed', callback),
  onToolWindowStateChange: (callback: (state: ToolWindowStatus) => void) => subscribe('tool-window:state-changed', callback),
  onToolWindowActivityChange: (callback: (active: boolean) => void) => subscribe('tool-window:activity-changed', callback),
  onToolWindowControlsVisibilityChange: (callback: (visible: boolean) => void) => subscribe('tool-window:controls-visibility-changed', callback),
  onJsonVaultChange: (callback: (relativePath: string) => void) => subscribe('json-vault:changed', callback),
  onQuickNoteVaultChange: (callback: (relativePath: string) => void) => subscribe('quick-note:vault-changed', callback),
  onRuntimeOutput: (callback: (event: RuntimeOutputEvent) => void) => subscribe('runtime:output', callback),
  onAiAgentTaskOutput: (callback: (event: AiAgentTaskOutputEvent) => void) => subscribe('ai:agents:task-output', callback),
  onAiModelRuntimeActionProgress: (callback: (event: AiModelRuntimeActionProgressEvent) => void) => subscribe('ai:model-runtime:action-progress', callback),
  onAiMemoryEmbeddingProgress: (callback: (event: AiMemoryEmbeddingProgressEvent) => void) => subscribe('ai:memory:embedding-progress', callback),
  onUpdateCheck: (callback: (event: UpdateCheckEvent) => void) => subscribe('update:checked', callback),
  onUpdateStateChange: (callback: (state: UpdateDownloadState) => void) => subscribe('update:state-changed', callback)
})

function subscribe<T>(channel: string, callback: (payload: T) => void): () => void {
  const listener = (_event: IpcRendererEvent, payload: T) => callback(payload)
  ipcRenderer.on(channel, listener)
  return () => ipcRenderer.removeListener(channel, listener)
}
